navikt/modiapersonoversikt

- package-lock.json
- package.json
- src/App.tsx
- src/components/person/PersonPage.tsx
- src/components/personside/Personside.tsx
- src/components/startbilde/Startbilde.tsx
- src/components/startbilde/startbilde.less
- src/components/visittkort/visittkort-container.tsx
- src/index.less
- src/redux/reducer.ts
- src/store.ts
Legg til en PersonPage som skal være mor-komponenten for all informasjon relatert til en person.
> Legg til en PersonPage

- package-lock.json
- package.json
- src/App.tsx
- src/components/person/PersonPage.tsx
- src/routing.tsx
Brukes for å holde styr på om du har en person i kontekst eller ikke.
> Legg til React-router for routing

- src/components/personside/Personside.tsx
- src/components/visittkort/Visittkort.less
- src/components/visittkort/Visittkort.tsx
- src/components/visittkort/visittkort-container.tsx
- src/ducks/person.ts
- src/ducks/utils.ts
- src/index.less
- src/innholdslaster.tsx
- src/redux/reducer.ts
- tsconfig.json
Reducer og logikk for å hente persondata. Det er mocket enn så lenge :)
> Legg til logikk og reducer for å hente persondata

- app.json
Fikk svar på ticketen til Heroku 😏
> [temp] Config for environment on heroku

- package-lock.json
- package.json
- src/app/personside/visittkort/Epost.tsx
- src/app/personside/visittkort/body/Epost.tsx
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/mock/person-mock.ts
- src/models/person.ts
Finnes ikke i backenden, enda så vil vel kanskje brekke når det kjører uten mock 🤔
> Lagt til epost-visning

- src/app/personside/visittkort/body/bankkonto/Bankkonto.tsx
- src/app/personside/visittkort/body/telefon/Mobiltelefon.tsx
- src/mock/person-mock.ts
- src/utils/helpers.test.ts
- src/utils/helpers.ts
> Formatering av bankkonto og telefonnummer

- src/stories/index.stories.tsx
- src/stories/responsive-columns/EventListener.tsx
- src/stories/responsive-columns/FloatingChildren.tsx
- src/stories/responsive-columns/ResponsiveFlexColumns.tsx
Noen løsninger for å løse responsivt layout i visittkortbody. Den eneste løsningen som løser dette fullt ut mtp skisser er løsningen med event-listener. Kom gjerne med alternative løsninger
> storybook, løsningsforslag til responsivt layout i visittkortbody

- src/app/personside/visittkort/Visittkort.test.tsx
- src/app/personside/visittkort/body/VisittkortBody.test.tsx
- src/app/personside/visittkort/header/VisittkortHeader.test.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personside/visittkort/header/status/Antallbarn.tsx
- src/app/personside/visittkort/header/status/PersonStatus.tsx
- src/app/personside/visittkort/header/status/Sivilstand.tsx
- src/menyConfig.ts
- src/mock/kontaktinformasjon-mock.ts
- src/mock/navkontor-mock.ts
- src/mock/oppgave-mock.ts
- src/mock/person/aremark.ts
- src/mock/person/bankkontoMock.ts
- src/mock/person/familerelasjonerMock.ts
- src/mock/person/personMock.ts
- src/mock/person/sivilstandMock.ts
- src/mock/setup-mock.ts
- src/mock/utils/fetch-utils.ts
- src/mock/utils/fnr-utils.ts
- src/mock/utils/mock-utils.ts
- src/models/person.ts
- src/stories/index.stories.tsx
Har også refaktorert i mock-setupen. Mye av endringene er bare flytting av kode.
> Familierelasjoner og visning i visittkort-header

- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/tilrettelagtkommunikasjon/TilrettelagtKommunikasjon.tsx
Om bruker har flere ulike vises disse på hver sin linje slik som i eksisterende ModiaBrukerdialog / ModiaPersonoversikt.
OPP-402
> Forenklet visningen av tilrettelagtInformasjon.

- src/mock/setup-mock.ts
For å "tvinge" oss til å bedre tenke på hvordan feilmeldinger, feilhåndtering osv. skal være, legger jeg på at når vi mock så feiler 10% av kallene vi gjør til backenden.
Vi kan se hvordan det funker eller om det bare blir irriterende. 
Inspirert av Netflix sin Chaos Monkey ™️
> Innfør feil for fåtall av tjenestekall

- src/utils/endretAvUtil.test.ts
- src/utils/endretAvUtil.ts
> Rettet slik at endretAv-metode ikke bryr seg om caseing paa ident.

- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/adresse/Adresse.tsx
- src/app/personside/visittkort/body/bankkonto/Bankkonto.tsx
- src/app/personside/visittkort/header/status/Antallbarn.tsx
- src/models/personadresse.ts
> OPP-396 Fikset en del feilrapporter og småendringer

- src/api/navkontor.test.js
- src/api/navkontor.ts
- src/app/personside/visittkort/body/navkontor/NavKontor.tsx
- src/app/personside/visittkort/header/NavKontorContainer.tsx
- src/redux/navkontor.ts
- src/redux/personinformasjon.ts
Dette siden geografisk-tilknytning kan være tom dersom det er satt diskresjonskode.
OPP-395
> Implementert endringer etter Breaking change på REST-endepunkt for Navkontor

- Procfile
- app.json
- heroku.yml
> Testing for kjøring på heroku

- README.md
- entrypoint.sh
- nginx.conf
- package.json
- public/index.html
- src/api/config.ts
- src/app/App.tsx
- src/setupTests.ts
> Add port for heroku-deployment

- src/app/personside/visittkort/body/kontaktinformasjon/NavKontaktinformasjon.tsx
- src/mock/person/aremark.ts
- src/mock/person/navKontaktinformasjon.ts
- src/models/person/NAVKontaktinformasjon.ts
- src/utils/telefon-utils.ts
- src/utils/telefonUtils.test.ts
kunne skille på de
Trenger dette i brukerprofil der man skal kunne endre retningsnummer
separat fra selve telefonnummeret.
> Splittet telefonnummer i retningsnummer og telefonnummer for lettere

- src/app/brukerprofil/BrukerprofilForm.tsx
- src/app/brukerprofil/EndreNavnForm.tsx
- src/app/brukerprofil/endrenavn/EndreNavnForm.tsx
- src/app/brukerprofil/endrenavn/Infomelding.tsx
- src/app/brukerprofil/endrenavn/endrenavn-utils.ts
> Valider at navn ikke er tomt når man redigerer navn i brukerprofil

- README.md
> Legger til CodeClimate badge

- .travis.yml
- Dockerfile
- publish.sh
> Gjør klart for autopublish av npm-pakke

- package-lock.json
- package.json
- src/app/brukerprofil/BrukerprofilForm.tsx
- src/app/personside/visittkort/Visittkort.tsx
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/components/ErrorBoundary.tsx
- src/components/StandAloneVisittkort/VisittKortStandAlone.tsx
> Lagt til React Error Boundries som skal catche runtime feil som skjer i

- src/app/brukerprofil/endrenavn/endrenavn-utils.ts
> Sjekket utvandret på feil element, fikset dette.

- src/app/personside/visittkort/header/VisittkortHeader.tsx
- src/mock/person/aremark.ts
Kan ikke bruke sammensattnavn fra TPS.
OPP-396
> Riktig format på navn i visittkort

- src/app/personside/visittkort/body/kontaktinformasjon/epost/Epost.tsx
- src/app/personside/visittkort/body/kontaktinformasjon/telefon/Mobiltelefon.tsx
- src/mock/kontaktinformasjon-mock.ts
- src/models/kontaktinformasjon.ts
> Reservasjon mot kommunikasjon på nett

- src/app/personside/visittkort/header/Etiketter.tsx
> Diskresjonskoder annet enn SPFS eller SPFO ignoreres 

- src/api/brukerprofil/endre-navkontaktinformasjon-api.ts
- src/app/brukerprofil/kontaktinformasjon/KontaktinformasjonForm.tsx
- src/app/personside/visittkort/body/kontaktinformasjon/NavKontaktinformasjon.tsx
- src/mock/person/navKontaktinformasjonMock.ts
- src/mock/person/personMock.ts
- src/models/person/NAVKontaktinformasjon.ts
- src/redux/brukerprofil/kontaktinformasjon.ts
- src/utils/string-utils.ts
Testet mot t6. Var litt mismatch mellom tjeneste og frontend.
Jeg har lyst å teste ut pact etterhvert 📦
> Kontaktinformasjon — tilpasninger til backend

- src/app/personside/visittkort/body/VisittkortElement.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/vergemal/Vergemal.test.tsx
- src/app/personside/visittkort/body/vergemal/Vergemal.tsx
Sjekk det ut her: https://modiapersonoversikt-pr-206.herokuapp.com/modiapersonoversikt/person/18070700030
Screenshot for den late:
> Vergemål designendringer

- app.json
Vil forhåpentlig redirecte alle lenker til review-apps på pull-requester
til korrekt URL
> Redirect bruker til korrekt url på en heroku-deploy

- src/app/brukerprofil/adresse/MidlertidigAdresseNorge.tsx
og velger denne i dropdown i brukerprofil
> Sjekker hvilken midlertidig adressetype som er satt 

- src/api/brukerprofil/adresse-api.ts
- src/app/brukerprofil/adresse/AdresseContainer.tsx
- src/app/brukerprofil/adresse/AdresseForm.tsx
- src/app/brukerprofil/adresse/GateadresseForm.tsx
- src/app/brukerprofil/adresse/MidlertidigAdresseNorge.tsx
- src/mock/utils/mock-utils.ts
- src/redux/brukerprofil/endreAdresseReducer.ts
- src/utils/dateUtils.ts
Tilpasninger til server, endret litt på noen felter.
> (Brukerprofil/adresser) Tilpasninger til Backend

- src/app/brukerprofil/adresse/midlertidigAdresseNorge/gateadresse/gateadresseValidator.ts
- src/app/brukerprofil/adresse/midlertidigAdresseNorge/matrikkeladresse/matrikkeladresseValidator.ts
- src/app/brukerprofil/adresse/midlertidigAdresseNorge/postboksadresse/postboksadresseValidator.ts
- src/utils/dateUtils.test.ts
- src/utils/dateUtils.ts
- src/utils/forms/commonValidatorRegler.ts
TPS krever at datoen er etter datoen idag.
> Valider gyldig-til dato for adresser i brukerprofilen

- src/app/brukerprofil/kontonummer/EndreKontonummerForm.tsx
- src/app/brukerprofil/kontonummer/kontonummerUtils.ts
- src/mock/person/bankkontoMock.ts
- src/models/person/person.ts
Det er forskjell på undefined og null - backenden returner null på
bankkonto om denne ikke finnes. Oppdaterer derfor personmodellen i
henhold.
> Retter feil der vi aksesserte en null-variabel

- package-lock.json
- src/app/brukerprofil/adresse/AdresseForm.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/LandInput.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/MidlertidigAdresseUtland.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/VelgLand.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/VelgLandContainer.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/midlertidigAdresseUtlandValidator.ts
- src/app/brukerprofil/kontonummer/UtenlandskKontonummerInputs.tsx
- src/app/brukerprofil/kontonummer/__snapshots__/EndreKontonummerForm.test.tsx.snap
- src/app/brukerprofil/kontonummer/utenlandskKontoValidator.ts
- src/components/forms/Datovelger.tsx
- src/mock/veilderRoller-mock.ts
- src/utils/kodeverkUtils.ts
* validering av utenlandsk adresse
* sorterer landnavn i dropdown
* div
> Utenlandsk adresse

- public/index.html
Varmer opp etter ferie med en liten PR.
> Fjern kommentarer fra boilerplate-koden

- src/api/oppgave-api.ts
- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/startbilde/Startbilde.tsx
- src/redux/restReducers/oppgaver.ts
Har også fjernet enhet fra oppgave-api metoden. Dette hentes ut fra
cookien på backenden.
> Endre fra GET til POST etter endringer i API

- package-lock.json
- package.json
Tror den henger igjen fra når vi dro inn Storybook.
> Fjern unødvendig dependency

- README.md
Fikser kreativ alfabetisering og fjerner meg selv.
> Rydd i kontaktpersoner i README

- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/familie/ListeAvBarn.tsx
- src/app/personside/visittkort/body/familie/common/Kjønn.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/components/person/HarSammeBosted.tsx
- src/components/person/NavnOgAlder.tsx
- src/mock/person/aremark.ts
- src/mock/person/familierelasjoner/familerelasjonerMock.ts
- src/models/person/person.ts
- src/utils/fnr-utils.ts
Disse blir ikke sendt med fra backenden hvis et familiemedlem har
diskresjonskode.
> Gjør felter optional som kan mangle når en familierelasjon har diskresjonskode

- src/app/personside/MainLayout.tsx
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/InfotabsContainer.tsx
- src/app/personside/infotabs/TabKnapp.tsx
- src/app/personside/infotabs/TabPanel.tsx
- src/app/personside/infotabs/utbetalinger/utbetalinger.tsx
- src/app/personside/infotabs/utbetalinger/utbetalingerContainer.tsx
- src/app/personside/visittkort/header/Etiketter.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/mock/setup-mock.ts
- src/mock/utbetalinger-mock.ts
- src/redux/restReducers/personinformasjon.ts
- src/redux/restReducers/utbetalinger.ts
Lager container og kobler opp mot reducere, sett opp mock pluss basic visningkomponent for utbetalinger intil vi har skisser fra designere.
> Utbetalinger komponent

- src/mock/utils/mock-utils.ts
- src/mock/ytelse/foreldrepenger-mock.ts
- src/mock/ytelse/pleiepenger-mock.ts
- src/mock/ytelse/sykepenger-mock.ts
- src/mock/ytelse/ytelse-utbetalinger-mock.ts
- src/models/ytelse/foreldrepenger.ts
- src/models/ytelse/pleiepenger.ts
- src/models/ytelse/sykepenger.ts
> OPP-517 Lager mock data for ytelser

- src/app/personside/infotabs/utbetalinger/Filter.tsx
- src/app/personside/infotabs/utbetalinger/TotaltUtbetalt.tsx
- src/app/personside/infotabs/utbetalinger/TotaltUtbetaltDetaljer.tsx
- src/app/personside/infotabs/utbetalinger/Utbetalinger.tsx
- src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.tsx
- src/app/personside/infotabs/utbetalinger/UtbetaltTilValg.tsx
- src/app/personside/infotabs/utbetalinger/YtelseValg.tsx
- src/app/personside/infotabs/utbetalinger/utbetalingerUtils.test.ts
- src/app/personside/infotabs/utbetalinger/utbetalingerUtils.tsx
- src/components/LazySpinner.tsx
- src/mock/person/aremark.ts
- src/mock/person/personMock.ts
- src/mock/utbetalinger-mock.ts
- src/redux/restReducers/restReducer.ts
- src/utils/string-utils.ts
Mulighet til å filtrere utbetalinger på hvem de er utbetalt til og hvilke ytelser det gjelder
> Utbetalinger filter

- src/components/person/NavnOgAlder.test.tsx
- src/components/person/NavnOgAlder.tsx
> Lagt til støtte for null-alder (viser ikke dette).

- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/lenkebrukerprofil/LenkeBrukerprofil.tsx
- src/app/personside/visittkort/body/lenkebrukerprofil/LenkeBrukerprofilContainer.tsx
- src/app/routes/routing.tsx
- src/mock/featureToggle-mock.ts
- src/mock/setup-mock.ts
- src/models/featureToggle.ts
- src/redux/restReducers/featuretoggle.ts
- src/redux/restReducers/personinformasjon.ts
- src/setupTests.ts
This reverts commit 04705120fed04cba0c6916ed672e1818d5f728c1.
> Revert "Fjerner feature toggle på ny brukerprofil"

- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/filter/UtbetaltTilValg.tsx
- src/mock/person/personMock.ts
- src/mock/statiskMockUtbetaling.ts
- src/mock/utbetalinger-mock.ts
- src/models/utbetalinger.ts
resterende blir liggende som egne linjer pr arbeidsgiver
> Samler utbetalinger til bruker i eget filter med navn Bruker

- public/index.html
This reverts commit 0b1260c9ca3a6f5a7ff52b034392c11b16eef1d0.
> Revert "Test med doorbell-feedbackløsning"

- src/app/brukerprofil/adresse/AdresseForm.tsx
- src/app/brukerprofil/adresse/__snapshots__/AdresseForm.test.tsx.snap
- src/app/brukerprofil/adresse/midlertidigAdresseNorge/MidlertidigAdresseNorge.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/MidlertidigAdresseUtland.tsx
- src/app/brukerprofil/endrenavn/EndreNavnForm.tsx
- src/app/brukerprofil/endrenavn/__snapshots__/EndreNavnForm.test.tsx.snap
- src/app/brukerprofil/kontonummer/__snapshots__/EndreKontonummerForm.test.tsx.snap
- src/app/brukerprofil/kontonummer/kontonummerUtils.ts
- src/app/brukerprofil/utils/formUtils.tsx
- src/mock/person/aremark.ts
- src/mock/person/personMock.ts
- src/models/person/person.ts
I brukerprofilen skal man vise endret av, men man skal vise utvidet info, så man kan ikke formattere bort info.
> Viser endret av i brukerprofil

- src/app/personside/infotabs/utbetalinger/DetaljerCollapse.tsx
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetaltDetaljer.tsx
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/__snapshots__/TotaltUtbetaltDetaljer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/UtbetalingsDetaljer.test.tsx.snap
- src/app/personside/visittkort/header/Etiketter/EtiketterContainer.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personside/visittkort/header/navkontor/NavKontorContainer.tsx
- src/components/AriaNotification.tsx
- src/components/Innholdslaster.tsx
- src/mock/egenansatt-mock.ts
- src/mock/person/vergemal/vergemalMock.ts
- src/redux/restReducers/restReducer.ts
Litt div.
Viktig endring i restReducer:
* resetter rest-reducer ved actiontypes.STARTING
- dette bør regresjonstestes ganske grundig
> Div fixes2

- src/app/brukerprofil/adresse/__snapshots__/AdresseForm.test.tsx.snap
- src/components/forms/Datovelger.tsx
> Hurtigvalg datovelger

- src/components/standalone/UtbetalingsLamell.tsx
Første skritt for å få utbetalinger inn i gamle modia.
> Standalone lamell for utbetalinger

- src/app/brukerprofil/BrukerprofilSide.tsx
- src/utils/environment.ts
- src/utils/frontendLogger.ts
Legger også til sjekk som sørger for at det kun logges i miljø
> Fikse brukerprofil bug

- package-lock.json
- src/app/personside/MainLayoutStyles.tsx
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/TabKnapper.tsx
- src/app/personside/infotabs/saksoversikt/DokumentKomponent.tsx
- src/app/personside/infotabs/saksoversikt/DokumentOgVedlegg.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/redux/reducers.ts
- src/redux/saksoversikt/saksoversiktStateReducer.ts
Nå vises ikke dokument som modal lenger, men i samme flate som saksoversikten
> Saksoversikt dokumentvisning

- package-lock.json
- src/app/brukerprofil/kontonummer/EndreKontonummerForm.tsx
- src/app/brukerprofil/kontonummer/UtenlandskKontonummerInputs.tsx
- src/app/brukerprofil/kontonummer/__snapshots__/EndreKontonummerForm.test.tsx.snap
- src/app/brukerprofil/kontonummer/kontonummerUtils.ts
- src/app/brukerprofil/kontonummer/norskKontoValidator.ts
- src/app/brukerprofil/kontonummer/utenlandskKontoValidator.ts
Slik blir ikke et kontonummer fra norsk defaultet inn i utenlandsk og vice versa når vi trykker på radioknappene.
Slik unngår vi også å miste arbeid som kan ha blitt skrevet inn i de forskjellige.
OPP-610
> Skiller mellom norsk og utenlandsk kontonummer i brukerprofile

- src/app/personside/infotabs/saksoversikt/DokumentKomponent.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/mock/saksoversikt/dokumentmetdata-mock.ts
Har også lagt inn personreducer slik at denne kan leve standalone.
> Vise riktig avsender og mottaker

- src/app/personside/infotabs/saksoversikt/DokumentKomponent.tsx
- src/app/personside/infotabs/saksoversikt/DokumentOgVedlegg.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/SakstemaVisning.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/mock/saksoversikt/dokumentmetdata-mock.ts
- src/redux/saksoversikt/saksoversiktStateReducer.ts
Da har jeg fikset opp i tilbakemeldinger :)
> Fikset tilbakemeldinger

- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/utils/LenkepanelPersonoversikt.tsx
_blank target, så om det er vindu eller fane er avhengig av browser
> Åpner nå lenkene til Arena og Norg i ny fane/vindu

- package-lock.json
- package.json
- src/app/App.tsx
- src/app/brukerprofil/BrukerprofilSide.tsx
- src/app/personside/MainLayoutStyles.tsx
- src/app/personside/ResponsiveMainLayoutStyles.tsx
- src/app/personside/infotabs/TabKnapper.tsx
- src/app/personside/infotabs/saksoversikt/DokumentKomponent.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/DelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/EnkelUtbetaling.tsx
- src/app/personside/visittkort/VisittkortContainer.tsx
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/header/Etiketter/SikkerhetstiltakEtikett.tsx
- src/app/personside/visittkort/header/VisittkortHeader.tsx
- src/app/startbilde/StartBildeLayout.ts
- src/components/DetaljerCollapse.tsx
- src/components/FillCenterAndFadeIn.ts
- src/components/VisMerKnapp.tsx
- src/components/common-styled-components.tsx
- src/components/component-placeholder/ComponentPlaceHolder.tsx
- src/components/pilknapp.tsx
- src/styles/personOversiktTheme.ts
Bumper styled components og jest-styled-components
En del boilerplate-endringer med bump av styled components.
Versjonen av jest-styled-components er en @next-versjon, men tenker at det kanskje går bra da dette kun brukes i test og ikke prod..?
> Bumpe styled components

- src/app/personside/infotabs/saksoversikt/DokumentOgVedlegg.tsx
Lager et varsel på dokumentvisning som i gammel løsning.
> Varsel på objekt

- src/app/personside/visittkort/HandleVisittkortHotkeys.tsx
- src/utils/loggSkjermInfoDaglig.ts
- src/utils/runOnceDaily.ts
Vil gjerne ha med denne i prodsettinga i morgen, så fint om dere kan se over kjapt :-)
> logger unike brukere av hurtigtaster i visttkort

- src/app/personside/Personside.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/ForeldrePenger.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/ForeldrepengerEkspanderbartPanel.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/Oversikt.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/foreldrePengerUtils.test.ts
- src/app/personside/infotabs/ytelser/foreldrepenger/foreldrePengerUtils.ts
- src/app/personside/infotabs/ytelser/pleiepenger/Arbeidsforhold.tsx
- src/mock/ytelse/foreldrepenger-mock.ts
- src/models/ytelse/foreldrepenger.ts
Utvider også mockdata
Fikser mindre skrivefeil
> Utvider foreldrepengeobjektet med manglende felter.

- src/components/tooltip/ToolTip.tsx
- src/utils/reactRefUtils.ts
Tooltip lukkes ikke automatisk etter 5 sekunder, men lukkes når man trykker utenfor
> Tooltipfix

- src/app/personside/infotabs/utbetalinger/totalt utbetalt/__snapshots__/TotaltUtbetaltDetaljer.test.tsx.snap
- src/app/personside/infotabs/ytelser/felles-styling/CommonStylingYtelser.ts
- src/app/personside/infotabs/ytelser/felles-styling/YtelserBullet.tsx
- src/app/personside/infotabs/ytelser/felles-styling/YtelserInfoGruppe.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/Oversikt.tsx
- src/app/personside/infotabs/ytelser/pleiepenger/Oversikt.tsx
- src/app/personside/infotabs/ytelser/pleiepenger/Pleiepengerperiode.tsx
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/pleiepenger.test.tsx
- src/styles/personOversiktTheme.ts
Styling på pleiepenger.
Pleiepengerpanelet ser nå litt bedre ut etter gjennomgang med designer.
Dette påvirker også alle grå paneler i personoveriskten som ikke lenger har border men en hvit kant. Dette er @agnethesh skikkelig fornøyd med ;-)
> Pleiepenger fixes

- src/components/standalone/VisittKort.tsx
Merk: Denne er ikke en del av visittkortet i personoversikten
> Legger kontrollspørsmål til standalone visittkort

- src/app/personside/kontrollsporsmal/SporsmalOgSvar.tsx
> Ikke bruk child-selector slik at modiabrukerdialog ikke hijacker stylen

- src/components/standalone/VisittKort.tsx
> Style kontrollspørsmål over visittkortet i standalone-visttkort

- src/app/personside/infotabs/ytelser/YtelserContainer.tsx
- src/app/personside/infotabs/ytelser/felles-styling/CommonStylingYtelser.ts
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/pleiepenger.test.tsx
- src/app/personside/infotabs/ytelser/pleiepenger/pleiepengerTestData.ts
- src/components/standalone/Pleiepenger/PleiepengerLaster.tsx
- src/styles/personOversiktTheme.ts
Minifiks på styling i pleiepenger etter ønske fra produkteier
> Pleiepenger fiks

- src/api/saf.ts
- src/app/brukerprofil/saf/SafForm.tsx
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/redux/restReducers/restReducers.ts
- src/redux/restReducers/saf/safReducer.ts
- src/redux/restReducers/saf/safRequest.ts
merger denne og ruller tilbake når jeg har fått testet det.
> Spike på saf-intergrasjon direkte fra frontend.

- src/app/brukerprofil/BrukerprofilSide.tsx
- src/app/personside/PersonsideContainer.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktMicroFrontend.tsx
- src/app/personside/kontrollsporsmal/Header.tsx
- src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx
- src/app/personside/kontrollsporsmal/skjulPåTversAvVinduerUtils.ts
- src/components/standalone/VisittKortLaster.tsx
- src/redux/kontrollSporsmal/actions.ts
- src/redux/kontrollSporsmal/reducer.ts
- src/redux/kontrollSporsmal/types.ts
- src/redux/restReducers/oppslagNyBruker.ts
- src/redux/restReducers/personinformasjon.ts
* sørger for at kontrollspørsmål for bruker forblir lukket på tvers av vinduer vha cookies
* sørger for at kontrollspørsmål blir resatt mellom brukere
* drar funksjon for å hente inn all data om person i egen fil og kaller den `oppslagNyBruker`
> Kontroll spørsmål fikses

- src/app/personside/infotabs/utbetalinger/HandleUtbetalingerHotKeys.tsx
- src/app/personside/infotabs/utbetalinger/Utbetalinger.test.tsx
- src/app/personside/infotabs/utbetalinger/Utbetalinger.tsx
- src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.tsx
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/filter/EgendefinertDatoInputs.tsx
- src/app/personside/infotabs/utbetalinger/filter/Filter.tsx
- src/app/personside/infotabs/utbetalinger/filter/UtbetaltTilValg.tsx
- src/app/personside/infotabs/utbetalinger/filter/YtelseValg.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/DelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/EnkelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/SammensattUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utils/utbetalingerUtils.test.tsx
- src/app/personside/infotabs/utbetalinger/utils/utbetalingerUtils.tsx
- src/redux/reducers.ts
- src/redux/utbetalinger/actions.ts
- src/redux/utbetalinger/types.ts
- src/redux/utbetalinger/utbetalingerReducer.ts
trekker også datovalg for egendefinerte datoer ut i egen fil
> refaktorering, legger filterstate for utbetalinger i redux

- src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> Feil tekst til hva som sjekkes.

- src/app/personside/infotabs/oppfolging/OppfolgingDetaljerKomponent.tsx
- src/models/oppfolging.ts
> Veileder er ikke obligatorisk

- src/app/personside/infotabs/oppfolging/OppfolgingDetaljerKomponent.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingVedtakKomponent.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingYtelserEkspanderbartPanel.tsx
- src/mock/oppfolging-mock.ts
- src/models/oppfolging.ts
> Datofikser på oppfolging og navn på veileder

- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/personside/kontrollsporsmal/KontrollSpørsmålKnapper.tsx
- src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx
- src/app/personside/kontrollsporsmal/cookieUtils.ts
- src/app/personside/kontrollsporsmal/skjulPåTversAvVinduerUtils.ts
For å styre visning, se OPP-732
> Cookies på kontrollspørsmål

- src/app/personside/kontrollsporsmal/KontrollSpørsmålKnapper.tsx
Gir ikke mening og kan kaste feil
> Skjuler "Nytt" knappen hvis vi ikke har noen spørsmål.

- src/app/personside/infotabs/oppfolging/OppfolgingVedtakKomponent.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingVisningKomponent.tsx
- src/app/personside/infotabs/oppfolging/SykefravarsoppfolgingEkspanderbartPanel.tsx
> skriver om info om sykefraværsoppfølging til tabell

- src/app/personside/infotabs/meldinger/MeldingerContainer.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/toppmeny/ToppMeny.tsx
- src/app/personside/infotabs/meldinger/toppmeny/ToppMenyContainer.ts
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/mock/meldinger/meldinger-mock.ts
- src/models/meldinger/meldinger.ts
Gjør noen småendringer for å gjøre klart til OPP-798 til OPP-806. Dette er på ingen måte ferdig, men en start så man har noe å jobbe videre på.
> Meldinger endringer

- src/app/personside/infotabs/oppfolging/OppfolgingContainer.test.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingYtelserEkspanderbartPanel.tsx
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/mock/oppfolging-mock.ts
- src/mock/statiskOppfolgingMock.ts
- src/models/oppfolging.ts
* Legger til manglende felter
* Trekker ut Dagpenger i eget interface (make the impossible impossible @jørund 🎺 )
> Oppfolging fikses

- src/app/personside/infotabs/ytelser/foreldrepenger/Oversikt.tsx
- src/app/personside/infotabs/ytelser/sykepenger/Sykepenger.tsx
- src/app/personside/infotabs/ytelser/sykepenger/arbeidsforhold/Arbeidssituasjon.tsx
- src/app/personside/infotabs/ytelser/sykepenger/sykemelding/Sykemelding.tsx
- src/app/personside/infotabs/ytelser/sykepenger/sykemelding/__snapshots__/Sykemelding.test.tsx.snap
- src/app/personside/infotabs/ytelser/sykepenger/sykepengertilfellet/Sykepengertilfellet.tsx
- src/app/personside/infotabs/ytelser/sykepenger/sykepengertilfellet/__snapshots__/Sykepengertilfellet.test.tsx.snap
- src/app/personside/infotabs/ytelser/utbetalinger/kommendeUtbetalinger/KommendeUtbetalingKomponent.tsx
- src/app/personside/infotabs/ytelser/utbetalinger/utførteUtbetalinger/UtførtUtbetaling.tsx
- src/components/DescriptionList.test.tsx
- src/components/DescriptionList.tsx
> Ytelser fikser

- .eslintrc
- .travis.yml
- package-lock.json
- package.json
- src/app/personside/infotabs/varsel/Varsler.tsx
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/visittkort/header/Etiketter/SikkerhetstiltakEtikett.tsx
- src/components/standalone/Tilbakemelding/TilbakemeldingPopup.tsx
- src/utils/frontendLogger.ts
Har fikset alle errors fra ts-lint, men har ikke fikset warnings. Tenker jeg kan ta dette i en ny PR når vi bla har funnet ut av æøå ;-)
> Bumpe til react-scripts 3.0

- src/app/personside/dialogpanel/DialogPanel.tsx
- src/app/personside/dialogpanel/Hurtigreferat/HurtigreferatContainer.test.tsx
- src/app/personside/dialogpanel/Hurtigreferat/HurtigreferatContainer.tsx
- src/app/personside/dialogpanel/Hurtigreferat/HurtigreferatElement.tsx
- src/app/personside/dialogpanel/Hurtigreferat/__snapshots__/HurtigreferatContainer.test.tsx.snap
- src/app/personside/dialogpanel/Hurtigreferat/tekster.ts
- src/components/featureToggle/toggleIDs.ts
- src/components/standalone/Hurtigreferat/HurtigreferatStandalone.tsx
- src/mock/featureToggle-mock.ts
- src/utils/stringFormatting.test.ts
- src/utils/stringFormatting.ts
Følger opp siste kommentarer fra forrige PR pluss featuretoggle og noen endringer på design og tekster
> Småfikser på hurtigreferat

- package-lock.json
- package.json
- src/app/brukerprofil/HandleBrukerprofilHotkeys.tsx
- src/app/brukerprofil/adresse/midlertidigAdresseUtland/MidlertidigAdresseUtland.tsx
- src/app/brukerprofil/kontaktinformasjon/KontaktinformasjonForm.tsx
- src/app/personside/Personside.tsx
- src/app/personside/infotabs/saksoversikt/viktigavite/ToggleViktigAaViteKnapp.tsx
- src/app/personside/visittkort/HandleVisittkortHotkeys.tsx
- src/app/personside/visittkort/VisittkortContainer.tsx
- src/app/routes/routing.tsx
- src/components/featureToggle/FeatureToggle.test.tsx
- src/components/featureToggle/FeatureToggle.tsx
- src/components/featureToggle/IfFeatureToggleOff.tsx
- src/rest/consumer/RestResourceConsumer.tsx
- src/setupTests.ts
- src/test/testStore.ts
- src/utils/forms/FormValidator.ts
> Bumpe react redux

- src/app/personside/dialogpanel/Hurtigreferat/__snapshots__/HurtigreferatContainer.test.tsx.snap
- src/app/personside/dialogpanel/Hurtigreferat/tekster.ts
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
> Endrer tekster i hurtigreferat ihht https://jira.adeo.no/browse/OPP-841

- src/components/standalone/Tilbakemelding/TilbakemeldingPopup.tsx
Husk å ikke bruke createRef i functional components, den lager alltid ny ref, bruk useRef()
OPP-875
> Fix at hele skjemaet ble refokusert bort fra tekstfelt ved hver update.

- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrePenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrepengePeriode.test.tsx.snap
- src/app/personside/infotabs/ytelser/utbetalinger/kommendeUtbetalinger/KommendeUtbetalinger.tsx
- src/app/personside/infotabs/ytelser/utbetalinger/kommendeUtbetalinger/__snapshots__/KommendeUtbetalinger.test.tsx.snap
Skriver om til react functional component heller enn ren funksjon for jsx
OPP-871
> Endrer tekst fra 'Utb.dato' til 'Reg.dato'

- src/components/standalone/Tilbakemelding/TilbakemeldingPopup.tsx
- src/components/standalone/VisittKort.tsx
> Oppdaterer tekst i tilbakemeldinger

- src/app/personside/dialogpanel/DialogPanel.tsx
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/JumpingDots.tsx
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/redux/oppgave/actions.ts
- src/redux/oppgave/reducer.ts
- src/redux/oppgave/types.ts
- src/redux/reducers.ts
- src/redux/uiReducers/UIReducer.ts
viser hvilken tråd man jobber på vha en liten animasjon i melding-panel
> legger valgt traad for dialogpanel i redux og kobler sammen meldingerog dialogpanel

- src/app/PersonOppslagHandler/LyttPåNyttFnrIReduxOgHentAllPersoninfo.tsx
- src/app/personside/dialogpanel/TildelteOppgaver.tsx
- src/redux/reducers.ts
- src/redux/restReducers/restReducers.ts
må også cache restResources i reducers.ts, hvis ikke blir alle restresources resatt uansett om vi har satt på caching lenger ned i reducer-treet
> legger til reducere som skal caches mellom brukere

- src/app/personside/infotabs/meldinger/MeldingerContainer.tsx
- src/app/personside/infotabs/oversikt/MeldingerOversikt.tsx
- src/app/personside/infotabs/oversikt/YtelserOversikt.tsx
- src/app/personside/infotabs/ytelser/YtelserContainer.tsx
- src/app/personside/infotabs/ytelser/useBrukersYtelser.tsx
* vise feilede kall mot ytelser
* håndtere at bruker ikke har noen meldinger
> Feilvisning ytelser og meldinger

- src/app/personside/MainLayoutStyles.tsx
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/fortsettDialog/__snapshots__/FortsettDialog.test.tsx.snap
- src/app/personside/dialogpanel/fortsettDialog/tidligereMeldinger/__snapshots__/TidligereMeldinger.test.tsx.snap
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/app/personside/infotabs/TabKnapper.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/__snapshots__/TotaltUtbetaltDetaljer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/SammensattUtbetaling.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/UtbetalingsDetaljer.test.tsx.snap
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/__snapshots__/YtelserContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/arbeidsforhold/__snapshots__/ArbeidsforholdListe.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrePenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/arbeidsforhold/__snapshots__/ArbeidsforholdListe.test.tsx.snap
- src/styles/personOversiktTheme.ts
Avklart med produkteier og designer.
Den andre committen inneholder snapshotoppdateringer, mye støy. Bør holde å se på første commit
> Oke kontrast

- src/app/personside/infotabs/TabKnapper.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/oversikt/Oversiktskomponent.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/varsel/Varsel.tsx
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/visittkort/header/VisittkortHeader.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/components/VisMerChevron.tsx
- src/components/VisMerKnapp.tsx
- src/styles/personOversiktTheme.ts
fra: 
til:
fra: 
til:
fra:
til:
fra:
til:
> Sma styling fikses

- src/app/App.tsx
- src/app/AppWrapper.ts
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/meldinger/MeldingerContainer.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingVisningKomponent.tsx
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/oversikt/Oversikt.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/saksdokumenter/SaksDokumenter.tsx
- src/app/personside/infotabs/saksoversikt/sakstemaliste/SakstemaListe.tsx
- src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.tsx
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/filter/Filter.tsx
- src/app/personside/infotabs/utils/InfoTabsScrollBar.ts
- src/app/personside/infotabs/varsel/Varsler.tsx
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/YtelserContainer.tsx
- src/app/personside/infotabs/ytelser/__snapshots__/YtelserContainer.test.tsx.snap
Anbefaler å lese en og en commit, så slipper dere støy fra snapshots
> Fikse scrollbars i lameller

- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
Meldinger fra bruker trenger ikke Lest/Ulest etikett. La inn sjekk før jeg legger på etikett på enkeltmelding
> [OPP-955] sjekk for om melding er fra bruker

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjema.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/byggRequest.ts
- src/models/meldinger/oppgave.ts
Gjør at opprett oppgave feiler på grunn av feil i payload.
> Legger på fnr på payload til oppgave

- src/app/personside/dialogpanel/TildelteOppgaver.tsx
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/fellesStyling.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/components/KnappMedBekreftPopup.tsx
Slettet bughunt/skrive-fixes branchen ettersom jeg ønsket å trekke ut delsvar-fix i en egen pull request og holde denne pull requesten liten. 
ting som er oppdatert: 
fjerne skrevet av felt på meldinger fra bruker
endre ordlyd til å skille mellom antall **tildelt oppgave / tildelte oppgaver** (entall/flertall)
endre navn på knappen lukk til **start ny dialog** i kvitteringspanel
**Avbryt** knapp dukker opp når du har påbegynt dialog
> Skrivefixes - ny branch

- src/app/personside/infotabs/meldinger/traadliste/besvarflere/BesvarFlere.tsx
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/SlåSammenOppgaverKnapp.tsx
- src/models/meldinger/meldinger.ts
hører sammen med https://github.com/navikt/modiabrukerdialog/pull/191
> Slaa sammen fixes

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjema.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjemaElementer.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/__snapshots__/OpprettOppgaveContainer.test.tsx.snap
Endrer visning på vellykket/feil så det stemmer overens med journalfør-panel
> Alert info

- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
Fixet overflow feil i ie11 på `traadlistelement`
> Overflow fix i Trådliste

- src/app/App.test.tsx
- src/app/App.tsx
- src/app/personsok/Personsok.tsx
- src/app/personsok/PersonsokSkjema.tsx
- src/app/personsok/PersonsokSkjemaElementer.tsx
- src/app/personsok/__snapshots__/PersonsokKomponent.test.tsx.snap
- src/app/personsok/personsokValidator.ts
> Minimumskriterier avansert søk

- src/app/personside/infotabs/oppfolging/OppfolgingContainer.test.tsx
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/oversikt/Oversikt.test.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/Utbetalinger.test.tsx
- src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.test.tsx
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetaltDetaljer.test.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/SammensattUtbetaling.test.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/UtbetalingsDetaljer.test.tsx
- src/app/personside/infotabs/utbetalinger/utils/utbetalingerUtils.test.tsx
- src/app/personside/infotabs/varsel/VarselContainer.test.tsx
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/YtelserContainer.test.tsx
- src/app/personside/infotabs/ytelser/__snapshots__/YtelserContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/pleiepenger.test.tsx
- src/mock/setup-mock.ts
- src/mock/utbetalinger/statiskMockUtbetaling.ts
- src/mock/utbetalinger/statiskMockUtbetalingRespons.ts
- src/mock/utbetalinger/utbetalinger-mock.ts
- src/mock/ytelse/foreldrepenger-mock.ts
- src/mock/ytelse/pleiepenger-mock.ts
- src/test/testStore.ts
- src/utils/dateUtils.test.ts
- src/utils/dateUtils.ts
> Sortering meldinger ie11 branch 2

- src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/saksdokumenter/SaksDokumenter.tsx
- src/app/personside/infotabs/saksoversikt/saksdokumenter/SaksDokumenterContainer.test.tsx
- src/app/personside/infotabs/saksoversikt/saksdokumenter/__snapshots__/SaksDokumenterContainer.test.tsx.snap
- src/mock/saksoversikt/saksoversikt-mock.ts
- src/utils/hooks/usePaginering.test.tsx
- src/utils/hooks/usePaginering.tsx
for brukere med veldig mange journalposter er saksoversikten ganske treg i ie11. Legger til paginering for journalposter som forslag til hvordan ytelsen kan forbedres i saksoversikten. 
Avklares med prod-eier
> POC paginering saksoversikt 

- src/app/personside/dialogpanel/DialogPanel.tsx
- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/personside/dialogpanel/TildelteOppgaver.tsx
- src/app/personside/dialogpanel/fellesStyling.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/leggTilbakePanel/LeggTilbakepanel.tsx
- src/app/personside/dialogpanel/fortsettDialog/useOpprettHenvendelse.tsx
- src/app/personside/dialogpanel/fortsettDialog/useVisTraadTilknyttetPlukketOppgave.tsx
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/SlåSammenOppgaverKnapp.tsx
- src/mock/oppgave-mock.ts
- src/models/oppgave.ts
- src/redux/restReducers/meldinger/opprettHenvendelse.ts
- src/rest/utils/restResource.ts
- src/utils/hooks/useTildelteOppgaver.test.ts
- src/utils/hooks/useTildelteOppgaver.ts
Bruker oppgaveid fra opprett henvendelse-kall i  fortsett dialogpanel
Renamer litt i oppgave-interface for å rydde opp i missforståelser
Er avhengig av https://github.com/navikt/modiabrukerdialog/pull/198
> Rydder litt i flyten i dialogpanelet

- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
En tilleggs-commit: Endrer i sjekk på vis sletting i merk-paneletet
> Kan ikke journalføre delsvar

- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
> Legger til feilsendt etikett

- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/TraadSammendrag.tsx
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
Setter dynamisk overflow på meldingspreview
> Setter dynamisk overflow på meldingstekst

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AutoComplete.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjemaElementer.tsx
- src/mock/meldinger/oppgave-mock.ts
- src/mock/setup-mock.ts
utvider også auto-complete-komponent til å kunne ta imot optional parameter topSuggestions som vil legge seg på toppen av suggestions-lista
denne avhenger også av PR i modiabrukerdialog
> foreslåtte enheter for lag oppgave

- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
Håndtering av nullverdier på journalføring-teksten
> Journalforing null

- src/app/App.tsx
- src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.tsx
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/utils/erNyPersonoversikt.ts
Fiks slik at Utbetalinger viser i gamle brukerdialog i chrome.
Også snapshot måtte oppdateres da dette påførte endringer i layout
> Fiks for at gamle brukerdialog viser utbetalinger i chrome.

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjemaElementer.tsx
> endret verdi til state og ikke konstant

- src/redux/restReducers/restReducers.ts
- src/utils/RollerUtils.tsx
Fikser evig spinner i hent oppgave:
> hindrer at veileder-roller blir resatt ved oppslag på ny person

- src/components/autocomplete-textarea/autocomplete-textarea.tsx
Fikser også hvordan word boundary finnes, den var litt feil når man pastet inn lang tekst
> Fikser cursor posisjonering og legger til ekstra magisk ord

- src/app/personsok/PersonsokSkjemaElementer.tsx
- src/app/personsok/__snapshots__/PersonsokKomponent.test.tsx.snap
> Avansert sok fix

- src/app/internarbeidsflatedecorator/Decorator.tsx
Er en special-case for modia, og tenker det derfor er greit å håndtere det der fremfor å bake det inn i dekoratøren
> [KAIZEN-0] nullstiller context ved 0-verdi fra puzzle

- package-lock.json
- package.json
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
og fjerner duplikat som ble oppdaget av nye typescriptversjonen
Her får vi optional chaning blant andre godsaker.
> bumper til siste versjon av typescript 3.7.2

- package-lock.json
- package.json
- src/app/personside/dialogpanel/fortsettDialog/leggTilbakePanel/LeggTilbakepanel.tsx
- src/app/personside/dialogpanel/sendMelding/TekstFelt.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjemaElementer.tsx
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/SammensattUtbetaling.test.tsx.snap
- src/app/personside/infotabs/ytelser/__snapshots__/YtelserContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrePenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrepengePeriode.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/sykepenger/sykemelding/__snapshots__/Sykemelding.test.tsx.snap
- src/app/personside/infotabs/ytelser/sykepenger/utbetalingerpåvent/__snapshots__/UtbetalingerPåVent.test.tsx.snap
- src/app/personside/infotabs/ytelser/utbetalinger/kommendeUtbetalinger/__snapshots__/KommendeUtbetalinger.test.tsx.snap
- src/app/personsok/__snapshots__/PersonsokKomponent.test.tsx.snap
- src/components/autocomplete-textarea/autocomplete-textarea.tsx
- src/components/standalone/Tilbakemelding/TilbakemeldingPopup.tsx
Bump av react-scripts førte til noen rare tregheter i collapse-animasjoner (og kanskje andre ting?). Prøvde å bumpe react og litt andre greier uten at det ordnet opp i feilen, foreslår å reverte denne til react-scripts har stabilisert seg litt
This reverts commit a7284d85b9f7d9d3764a374a8963f0931df4d5e8, reversing
changes made to ac2e4e6da1e59c7b2180ed1cd3be89b61b6733c6.
> Revert "Merge pull request #892 from navikt/bumper-react-scripts"

- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/oversikt/UtbetalingerOversikt.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/app/personside/infotabs/utbetalinger/Arenalenke/Arenalenke.tsx
- src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/__snapshots__/YtelserContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrePenger.test.tsx.snap
- src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrepengePeriode.test.tsx.snap
- src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap
- src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx
- src/app/personside/visittkort/body/VisittkortStyles.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/header/VisittkortHeader.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personsok/__snapshots__/PersonsokKomponent.test.tsx.snap
- src/styles/personOversiktTheme.ts
- src/utils/LenkepanelPersonoversikt.tsx
Sørger for at standard-marginer brukes til layout-formål og reduserer standardmarginen litt i samråd med produkteier. Vanlig tilbakemelding fra brukere at de vil ha mest mulig info på skjermen til enhver tid, dette bidrar litt til det.
> Standardisere marginer mer kompakt

- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/lenkebrukerprofil/LenkeBrukerprofil.tsx
Endringsønske fra personforvalter
> Tilrettelegg fix

- src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekstModal.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekstSok.tsx
- src/app/personside/infotabs/HandleInfotabsHotkeys.tsx
- src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingYtelserEkspanderbartPanel.tsx
- src/app/personside/infotabs/oppfolging/SykefravarsoppfolgingEkspanderbartPanel.tsx
- src/app/personside/infotabs/saksoversikt/dokumentvisning/DokumentOgVedlegg.tsx
- src/app/personside/infotabs/saksoversikt/saksdokumenter/JournalPoster.tsx
- src/app/personside/infotabs/utbetalinger/filter/Filter.tsx
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetalt.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/DelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/EnkelUtbetaling.tsx
- src/app/personside/infotabs/varsel/varselDetaljer/VarselMeldinger.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/ForeldrePenger.tsx
- src/app/personside/infotabs/ytelser/pleiepenger/Pleiepenger.tsx
- src/app/personside/infotabs/ytelser/sykepenger/Sykepenger.tsx
- src/utils/hooks/use-hotkey.ts
Og logger visning av en del sider og komponenter
> logger event for bruk av alle hurtigtaster

- public/index.html
- src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekstVisning.tsx
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/meldinger/__snapshots__/MeldingerContainer.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
Kommentarer fra David:
 ✅  Tabs -> radio
  ✅ Engelsk i tabmeny
  ✅ Tittel bør hvilken fane som er åpnet
  ✅ Tittel "Valgt melding", trener ikke "valgt melding"
  ✅ Gi tilbakemelding på hvilken tekst som er valgt i standardteskter ved pil opp/ned
> OPP-1052 skjermleserfixer

- src/app/personside/Personoversikt.tsx
- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/personside/dialogpanel/fortsettDialog/VelgDialogType.tsx
- src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx
- src/app/personside/visittkort/header/VisittkortHeader.tsx
- src/redux/session/session.ts
- src/utils/hooks/useJobberMedSTO.ts
dette skjedde fordi om man jobbet med STO ble utledet fra plukkOppgaveResource som blir resatt når man besvarer en melding.
legger derfor egen boolean "jobberMedSTO" i redux som settes/resettes ved mount av Personside (oppslag ny person)
> fikser bug med at kontrollspørsmål dukker opp når man besvarer en STO

- src/components/autocomplete-textarea/autocomplete-textarea.tsx
> fult navn på nav kontor brukere

- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/tilrettelagtkommunikasjon/TilrettelagtKommunikasjon.tsx
- src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/mock/person/aremark.ts
> [OPP-961] Endringer i visning av tilrettelagt kommunikasjon

- src/components/autocomplete-textarea/autocomplete-textarea.tsx
Kan lenkes opp til tekster fra modia-skrivestøtte med følgende konfig;
```
{
type: 'external',
regex: /^koro$/i,
externalId: '63c33692-08e8-45af-990d-e6a773cbcbb1' 
}
```
> [KAIZEN-0] la til støtte for å legge til hotkeys for standardtekster

- src/app/personside/dialogpanel/sendMelding/DialogpanelVelgSak.tsx
Løser opp i FAGSYSTEM-102253, FAGSYSTEM-102249 og FAGSYSTEM-102155
> [KAIZEN-0] passer på å hente data fra riktig url

- src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx
- src/app/personside/infotabs/meldinger/traadliste/__snapshots__/TraadListe.test.tsx.snap
- src/components/PrintKnapp.tsx
> OPP-1088 Print av alle meldinger

- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
Liten sjekk at dei nye sosial-kategoriene ikkje kan jorunalføres
> Opp 1116 journalforing

- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/models/meldinger/merk.ts
Her mangler det URL for nytt endepunkt
> [OPP1130] Frontend for merkoppgave - tvungen ferdigstillelse

- src/app/personside/infotabs/saksoversikt/SaksDokumentIEgetVindu.tsx
- src/app/personside/infotabs/saksoversikt/dokumentvisning/SaksDokumentVisning.tsx
> [KAIZEN-0] Styler på feilmeldinger i saker i eget vindu

- src/app/innstillinger/modal/innstillinger-modal-form.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/kontaktinformasjon/Kontaktinformasjon.tsx
- src/app/personside/visittkort/body/kontaktinformasjon/NavKontaktinformasjon.tsx
- src/mock/person/aremark.ts
- src/mock/person/moss.ts
- src/models/person/person.ts
Vil bare vises for brukere som er flyttet over til modiapersonoversikt-api da uthenting av telefonnummer fra pdl bare er implementert der.
> [OPP-1075] bruker telefonummer fra pdl om de er tilgjengelige

- src/app/personside/infotabs/saksoversikt/SakerFullscreenLenke.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
- src/utils/LenkepanelPersonoversikt.tsx
> [OPP-1184] bruker react-router Link for intern navigering

- package-lock.json
- package.json
Tilrettelegger for følgende;
```
useFormstate<STATE, PROPS>(validator: (values: STATE, props: PROPS) => Record<STATE, string | undefined>)
```
hvor det tidligere bare var mulig å gjøre;
```
useFormstate<STATE, PROPS>(validator: Record<STATE, FieldValidator>)
```
Dette betyr at følgende nå er gyldig;
```
useFormstate((verdier) => {
return {
felt1: verdier.felt1.length === 0 'Required' : undefined
};
})
```
> [KAIZEN-0] utvidet støtte av validering i formstate testing

- src/app/personside/infotabs/saksoversikt/SakerFullscreenLenke.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
> [KAIZEN-0] åpner fullscreen saksoversikt i ny fane

- src/app/personside/infotabs/meldinger/traadliste/besvarflere/__snapshots__/BesvarFlere.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
Endringsønske fra fagsystemsak. 
Husker ikke om dette var avklart at vi skulle vise det? Kathrine bør godkjenne
> [FAGSYSTEM-115721] Legger til lest dato og klokkeslett på meldinger

- src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts
- src/app/personside/Personoversikt.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/useVisTraadTilknyttetPlukketOppgave.tsx
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AvsluttGosysOppgaveSkjema.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/mock/oppgave-mock.ts
- src/models/meldinger/oppgave.ts
- src/utils/fetchToJson.ts
Avhengig av https://github.com/navikt/modiapersonoversikt-api/pull/170
> [PROD][OPP-1248] henter oppgave-data fra backend ved overgang fra gosys

- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
legg-tilbake panelet er fortsatt bak "erSTOOppgave"-sjekken slik at bare STO-oppgaver kan legges tilbake
> [KAIZEN-0] muliggjør ferdigstilling av ikke-sto-oppgaver via fortsettdialog

- src/app/personside/dialogpanel/fortsettDialog/useVisTraadTilknyttetPlukketOppgave.tsx
Ble tidligere logget om tråden ikke kunne besvares (e.g samtalereferat etc)
> [KAIZEN-0] logger kun feil om man ikke finner tråd fra oppgaveData

- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/VelgDialogType.tsx
delvis-svar med endring av temagruppe gir bare mening for STO-oppgaver.
> [KAIZEN-0] fjerner delvis-svar når oppgave ikke faller under STO

- src/app/personside/infotabs/oversikt/OppfolgingOversikt.tsx
> OPP1263 Lage copy to clipboard for veileder og ident

- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/components/autocomplete-textarea/autocomplete-textarea.tsx
Legger til forkortelser i autocomplete etter ønske fra NKS
> [KAIZEN-0] Autocomplete

- src/models/temagrupper.ts
Del 1 av fjerning av ort.hjelpemiddel
> [opp-1280] Fjerning av ort.hjelp som teamgruppe for tilbakelegg

- src/app/personsok/PersonsokSkjema.tsx
- src/app/personsok/__snapshots__/PersonsokKomponent.test.tsx.snap
> [KAIZEN-0] Fikset styling av Avansert Søk skjema

- src/models/temagrupper.ts
Del to, der plukk-muligheiten fjernes
> [opp-1280] Fjerning av ort.hjelpemiddel som teamgruppe for plukk

- src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekster.tsx
Oppdaterer `[saksbehandler.enhet]` til å vise enhet når man bruker `Signatur`
> [OPP-1309] sender inn enhet i byggAutofullforMap

- package-lock.json
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/foreldreansvar/Foreldreansvar.test.tsx
- src/app/personside/visittkort/body/foreldreansvar/Foreldreansvar.tsx
- src/app/personside/visittkort/body/foreldreansvar/__snapshots__/Foreldreansvar.test.tsx.snap
- src/mock/person/aremark.ts
- src/mock/person/doedsbo.ts
- src/mock/person/foreldreansvarMock.ts
- src/mock/person/moss.ts
- src/models/foreldreansvar/foreldreansvar.ts
- src/models/person/person.ts
> [OPP-1282] Foreldreansvar fra PDL

- src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts
- src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
- src/app/personside/infotabs/InfoTabEnum.ts
- src/app/personside/infotabs/InfoTabs.test.ts
- src/app/personside/infotabs/InfoTabs.tsx
- src/app/personside/infotabs/TabKnapper.tsx
- src/app/personside/infotabs/dyplenkeTest/meldingerDyplenker.test.tsx
- src/app/personside/infotabs/dyplenkeTest/sakerDyplenker.test.tsx
- src/app/personside/infotabs/dyplenkeTest/utbetalingDyplenker.test.tsx
- src/app/personside/infotabs/dyplenkeTest/ytelserDyplenker.test.tsx
- src/app/personside/infotabs/oversikt/Oversikt.tsx
- src/app/personside/infotabs/oversikt/Oversiktskomponent.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/utils/useOpenTab.ts
- src/app/routes/routing.tsx
Venter med å merge denne til #1510 er ute i prod
> [KAIZEN-0] Endrer håndteringen av Infotabs enum for å kunne skille mellom path og tittel for ulike tabs

- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/foreldreansvar/Foreldreansvar.tsx
- src/app/personside/visittkort/body/foreldreansvar/__snapshots__/Foreldreansvar.test.tsx.snap
- src/svg/Info.js
> [KAIZEN-0] leger til info-ikon paa foreldreansvar

- src/components/featureToggle/toggleIDs.ts
- src/mock/featureToggle-mock.ts
- src/utils/hooks/use-persistent-login.ts
Toggle har vært aktiv i produksjon siden september 2020 uten vesentlige problemstillinger.
> [KAIZEN-0] fjerne featuretoggle for utloggingsinfo

- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/VelgDialogType.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
> [OPP-1170] legger til muligheter for samtalereferat i fortsett dialog

- src/app/oppdateringslogg/EnkeltOppdateringslogg.tsx
- src/app/oppdateringslogg/config/config.tsx
Endrer til riktig id og fjerner samtidig unødvendig bruk av tags i oppdateringslogg config
> [KAIZEN-0] Endrer til riktig id i oppdateringslogg-config

- src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
Har kommet frem til at det er mest hensiktsmessig å beholde fokuset på år.
> [OPP-1337] Endrer fokus tilbake til år

- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/VelgDialogType.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/app/startbilde/Startbilde.tsx
@olofab 
Endringene relatert til opp-1170 var ikke 100%, så disse er revert og lagt inn i denne branchen for videre testing/utvikling
> [REVERT-0] henter inn igjen reverterte endringer

- package-lock.json
har transitiv avhengighet til path-parse som har et reDOS sikkerhets-issue
> [KAIZEN-0] oppgrader resolve-pakken

- .nais/prod.yaml
- .nais/qa-template.yaml
buttons innenfor ett form vil automatisk fungere som en submit knapp om ikke annet er spesifisert. Ved å sette type="button" skrus denne funksjonaliteten av.
> [PROD][FAGSYSTEM-185782] forhindre submit ved velgsak

- src/app/personside/dialogpanel/fortsettDialog/tidligereMeldinger/TidligereMeldinger.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
- src/app/personside/infotabs/utbetalinger/filter/Filter.tsx
- src/app/personside/infotabs/ytelser/YtelserListe.tsx
- src/app/personside/visittkort/body/VisittkortBody.tsx
- src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort/body/deltBosted/DeltBosted.tsx
- src/app/personside/visittkort/body/deltBosted/__snapshots__/DeltBosted.test.tsx.snap
- src/app/personside/visittkort/body/foreldreansvar/Foreldreansvar.tsx
- src/app/personside/visittkort/body/foreldreansvar/__snapshots__/Foreldreansvar.test.tsx.snap
- src/app/personside/visittkort/body/kontaktinformasjon/NavKontaktinformasjon.tsx
- src/app/personside/visittkort/body/lenkebrukerprofil/LenkeBrukerprofilContainer.tsx
- src/svg/Info.js
Etter jobb med visittkort i pdl-oppgavene kom det frem en del warnings i consollen for vår frontend.
Denne PR-en vil gjøre noen enkle forbedringer og litt refaktorering for å fikse opp i dette.
Spør gjerne eller kommenter hvis det er noe som ikke ser helt riktig ut, eller hvis man kan gjøre endringene på en bedre måte 👌🏼
> [KAIZEN-0] rette opp i warnings i frontend

- .github/workflows/gh-pages.yml
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/familie/Sivilstand.tsx
- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/mock/featureToggle-mock.ts
- src/mock/index.ts
- src/mock/meldinger/meldinger-mock.ts
- src/mock/persondata/aremark.ts
- src/mock/persondata/personDeltBosted.ts
- src/mock/persondata/personDod.ts
- src/mock/persondata/personEgenAnsatt.ts
- src/mock/persondata/personKode6.ts
- src/mock/persondata/personKode6Utland.ts
- src/mock/persondata/personKode7.ts
- src/mock/persondata/persondata.ts
Vi legger til en rekke mockpersoner basert på data fra PDL, og deployer dette til github pages for testing med blant annet blind bruker.
> [OPP-1390] Legger til mockdata

- package-lock.json
- package.json
- src/app/personside/dialogpanel/Preview.tsx
- src/app/personside/dialogpanel/fortsettDialog/tidligereMeldinger/EnkeltMelding.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/velgTekst/StandardTekstPreview.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/velgTekst/StandardTekstValg.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/velgTekst/StandardtekstListe.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/velgTekst/TekstListeElement.tsx
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/components/Tekstomrade.tsx
- src/utils/print/MeldingerPrintMarkup.tsx
- [KAIZEN-0] overstyrer tekstomrade lenker med noreferrer
- [KAIZEN-0] oppgraderer prettier
> [KAIZEN-0] fix/no referal

- .nais/prod.yaml
- .nais/qa-template.yaml
- Dockerfile
Grunnet endring i backend vil vi nå hente navn fra tredjepartsperson,
som endrer litt på formatet vi får navnet på.
Legger også ved test på dødsbo.
> [PROD][OPP-1390] utvide navn på personadressat

- src/app/personside/visittkort-v2/PersondataDomain.ts
Tidligere modell samsvarte ikke med hva som ble sendt fra backend.
Hadde ingen innvirkning på koden utover dette, men fint å ha på plass.
> [OPP-1390] endre datamodell for verge

- src/app/personside/visittkort-v2/body/familie/Familie.tsx
Tidligere modell samsvarte ikke med hva som ble sendt fra backend.
Hadde ingen innvirkning på koden utover dette, men fint å ha på plass.
> [PROD][OPP-1390] endre datamodell for verge

- src/app/personside/visittkort-v2/body/familie/ListeAvBarn.tsx
- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personside/visittkort-v2/header/status/AntallBarn.tsx
- src/app/personside/visittkort-v2/visittkort-utils.ts
Siden funksjonen sjekker mindre eller lik 21 (<=21) så blir det mer riktig å si barnUnder22.
> [OPP-1390] endre til 22 år basert på logikken

- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/body/familie/ListeAvBarn.tsx
- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personside/visittkort-v2/header/status/AntallBarn.tsx
- src/app/personside/visittkort-v2/visittkort-utils.ts
Siden funksjonen sjekker mindre eller lik 21 (<=21) så blir det mer riktig å si barnUnder22.
> [PROD][OPP-1390] endre til 22 år basert på logikken

- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/vergemal/Vergemal.tsx
- src/app/personside/visittkort-v2/body/vergemal/__snapshots__/Vergemal.test.tsx.snap
Denne ble pushet til feil branch, skulle egt rett i dev 🙃
> [OPP-1390] fjerne unødvendig felt med avsnitt

- src/app/brukerprofil/useUrlNyPersonforvalter.ts
- src/mock/index.ts
- src/test/testStore.ts
Vi endrer endepunktet som spør om aktorid til nye persondatacontroller.
> [OPP-1404] bruke nye v2 aktorid endepunkt

- src/app/personside/dialogpanel/sendMelding/Oppgaveliste.tsx
svar fra bruker vil da generere oppgave direkte til veileder/saksbehandler fremfor at oppgaven havner på enhetens benk
> [NKS-1045] fjerne sperre for ansatt-tilknyttning for oppgave

- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/varsel/Varsel.tsx
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
vis vise dato for original varsel og eventuell purring
> [FAGSYSTEM-191075] vise alle utsendingsdatoer for varsel

- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
> [KAIZEN-0] legge til alert om avsluttet tråd

- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- 0e42be99 [KAIZEN-0] endre sjekk for avsluttet
> [PROD] endre sjekk for avsluttet

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjema.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/skjermetPerson/OppgaveSkjemaSkjermetPerson.tsx
- src/mock/index.ts
- src/mock/meldinger/oppgave-mock.ts
- src/redux/restReducers/meldinger/gsakTema.ts
Formatet på den nye dataen er forhåpentligvis lik (🤞🏼) så da trengs det bare en oppdatering i hvilket endepunkt vi spør.
Denne kan ikke gå ut før backend-PR er på plass.
> [OPP-1415] ta i bruk nytt endepunkt for tema

- .github/workflows/main.yml
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/mock/featureToggle-mock.ts
siden vi ikke har mulighet til å sende inn årsak til sladding, så må det meldes sak i porten.
> [PROD][KAIZEN-0] vise advarsel ved bruk av sladding

- package-lock.json
- src/app/personside/dialogpanel/sendMelding/autofullforUtils.ts
- src/app/personside/infotabs/dyplenkeTest/meldingerDyplenker.test.tsx
- src/app/personside/infotabs/ytelser/foreldrepenger/foreldrePengerUtils.test.ts
- src/app/personside/kontrollsporsmal/KontrollSporsmalKnapper.tsx
- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/header/status/PersonStatus.tsx
- src/components/standalone/StandAloneKomponenter.tsx
- src/mock/persondata/aremark.ts
- src/mock/persondata/persondata.ts
- src/mock/personsok/personsokMock.ts
- src/mock/saksoversikt/saksoversikt-mock.ts
- src/mock/utbetalinger/utbetalinger-mock.ts
- src/mock/varsler/varsel-mock.ts
- src/mock/ytelse/foreldrepenger-mock.ts
- src/mock/ytelse/pleiepenger-mock.ts
- src/mock/ytelse/sykepenger-mock.ts
- src/test/testStore.ts
siden vi ikke kan garantere at en bruker har fnr endret vi variabelnavnet til personIdent. Dette feltet kan inneholder fnr, dnr, muligens hnr og bnr/npid.
> [PROD][FAGSYSTEM-208044] endre til bruke personident

- src/app/personside/Personoversikt.tsx
- src/app/startbilde/PersonSokInput.tsx
- src/utils/fnr-utils.ts
fnr-validator-pakken godtar ikke bost-nr eller npid. Modulos-sjekken alene skal fungere med alle personidenter
> [KAIZEN-0] forenkle ident validering

- src/app/oppdateringslogg/config/config.tsx
- e86d00df [KAIZEN-0] oppdatert tekst
> [PROD] [KAIZEN-0] oppdatert tekst

- .nais/prod.yaml
- .nais/qa-template.yaml
- fjerner ubrukt vault-config
- nedjusterer ressursbruk da appen er byttet til nginx
> [KAIZEN-0] justere nais-yaml

- src/app/oppdateringslogg/config/config.tsx
- fjerner ubrukt vault-config
- nedjusterer ressursbruk da appen er byttet til nginx
> [PROD][KAIZEN-0] justere nais-yaml

- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/mock/dialoger/sf-dialoger-mock.ts
- src/models/meldinger/merk.ts
- [OPP-1436] legge til merk-operasjon "avslutt dialog"
- [OPP-1436] vise alle markerings-infobokser
> [OPP-1436] lukk traad

- .github/workflows/gh-pages.yml
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap
Vi oppdaget at det var en liten css-feil i prod på checkboksene, og unngår denne "rariteten" med en liten fiks.
> [PROD][OPP-1422] fikse css-feil på checkbokser

- src/app/personside/dialogpanel/fortsettDialog/BrukerKanSvare.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/sendMelding/DialogpanelVelgSak.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.test.ts
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/components/featureToggle/toggleIDs.ts
- src/mock/featureToggle-mock.ts
vi filtrer bort saker som tråden allerede er journalført på.
> [OPP-1043] gjøre det mulig å journalføre tråder flere ganger

- src/api/api.ts
- src/app/personside/dialogpanel/Preview.tsx
- src/app/personside/dialogpanel/fellesStyling.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMeldingKvittering.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMeldingTypes.ts
- src/app/personside/dialogpanel/useSendtMelding.ts
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/mock/dialoger/sf-dialoger-mock.ts
- src/mock/mockBackend/meldingerBackendMock.ts
- src/models/meldinger/meldinger.ts
Hører med https://github.com/navikt/modiapersonoversikt-api/pull/731
Vi mottar nå tråden som opprettes ved kall til backend og kan bruke dette for sjekk på trådID istedet for meldingen.
> [OPP-1407] endre response ved dialoger

- src/app/oppdateringslogg/OppdateringsloggContainer.tsx
- src/app/oppdateringslogg/config/config.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/validatorer.ts
- src/app/personside/infotabs/meldinger/traadliste/__snapshots__/TraadListe.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/components/featureToggle/toggleIDs.ts
- src/mock/featureToggle-mock.ts
- src/mock/meldinger/meldinger-mock.ts
- src/mock/meldinger/statiskTraadMock.ts
- src/models/meldinger/meldinger.ts
- src/utils/print/MeldingerPrintMarkup.tsx
- [OPP-1043] fjerne featuretoggle for journalføring på flere saker
- [OPP-1043] oppdatere visning for print av meldinger
- [OPP-1043] fjerne journalførings info fra meldings-objektet
- [OPP-1043] rename funksjon
- [OPP-1043] oppdatere snapshot tester
> [OPP-1043] fix/opp 1043 ft og print

- src/components/featureToggle/toggleIDs.ts
siden toggle inneholder punktum må vi ha fullstendig featuretoggle navn med appnavn-prefiks.
> [PROD][KAIZEN-0] legge til prefiks for featuretoggle

- src/app/personside/infotabs/varsel/Varsel.tsx
- src/app/personside/infotabs/varsel/varsel-loader.tsx
- src/mock/varsler/statiskVarselMock.ts
- src/mock/varsler/varsel-mock.ts
- src/models/varsel.ts
- efc9b314f [KAIZEN-0] endre feltnavn for notifikasjons mottattdato
> [PROD] [KAIZEN-0] endre feltnavn for notifikasjons mottattdato

- Dockerfile
sender brukere til login om tokenet løper ut om 2minutter (tidligere 10min)
> [PROD][KAIZEN-0] bump host image

- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/fullmakt/Fullmakt.tsx
- src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap
- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/mock/persondata/aremark.ts
- src/mock/persondata/persondata.ts
Etter endringsønske fra bruker viser vi nå telefonnr på fullmakt.
> [OPP-1467] legge til tlf-nr for fullmakt

- .github/workflows/gh-pages.yml
- Dockerfile
- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/fullmakt/Fullmakt.tsx
- src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap
- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/mock/persondata/aremark.ts
- src/mock/persondata/persondata.ts
Etter endringsønske fra bruker viser vi nå telefonnr på fullmakt.
> [PROD][OPP-1467] legge til tlf-nr for fullmakt

- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/body/Endringstekst.tsx
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/kontaktinformasjon/dodsbo/__snapshots__/Dodsbo.test.tsx.snap
- src/mock/persondata/aremark.ts
- src/mock/persondata/persondata.ts
🔴 Må vente med å gå ut til etter at https://github.com/navikt/modiapersonoversikt-api/pull/813 er i prod
> [OPP-1481] Legger til kilde og oppdaterer endringstekst og snapshots

- src/app/personside/dialogpanel/use-draft.ts
- 67fb7793b [KAIZEN-0] sender med uuid som path-param til draft-app
> [PROD] [KAIZEN-0] sender med uuid som path-param til draft-app

- .nais/prod.yaml
- .nais/qa-template.yaml
- public/appDynamics.js
- src/app/internarbeidsflatedecorator/Decorator.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekster.tsx
- src/app/personside/dialogpanel/sendMelding/standardTekster/sokUtils.tsx
- src/app/personside/dialogpanel/use-draft.ts
- src/components/autocomplete-textarea/autocomplete-textarea.tsx
- src/mock/context-mock.ts
- src/mock/draft-mock.ts
- src/mock/index.ts
- src/mock/mock-websocket.ts
- src/mock/saksbehandlerinnstillinger-mock.ts
- src/redux/innstillinger.ts
kall til skrivestotte, draft, innstillinger og modiacontextholder gjøres via proxy slik at cookies kan låses ned til kun å gjelde modiapersonoversikt
> [PROD][KAIZEN-0] gjøre kall til modia-apper via proxy

- .nais/prod.yaml
- .nais/qa-template.yaml
- 7fcd69401 [KAIZEN-0] skru opp tilgjengelige ressurser
> [PROD] [KAIZEN-0] skru opp tilgjengelige ressurs

- .nais/prod.yaml
- Dockerfile
- bfe6b5e49 [KAIZEN-0] bump host image
- 881ca78c6 [KAIZEN-0] skru på azure ad i preprod
> [PROD] [KAIZEN-0] bump host image

- src/app/personside/infotabs/utbetalinger/MånedsGruppe.tsx
- src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetaltDetaljer.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/DelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/EnkelUtbetaling.tsx
- src/app/personside/infotabs/utbetalinger/utbetaling/UtbetalingsDetaljer.tsx
- src/app/personside/infotabs/utbetalinger/utils/utbetalinger-utils.test.tsx
- src/app/personside/infotabs/utbetalinger/utils/utbetalinger-utils.ts
- src/mock/utbetalinger/statiskMockUtbetaling.ts
- src/mock/utbetalinger/statiskMockUtbetalingRespons.ts
- src/mock/utbetalinger/utbetalinger-mock.ts
- src/models/utbetalinger.ts
Avhengig av https://github.com/navikt/modiapersonoversikt-api/pull/860
> [KAIZEN-0] bytte ut æøå i kode

- src/app/personside/dialogpanel/sendMelding/autofullforUtils.ts
- 7e203f204 [FAGSYSTEM-238338] kapitalisering av navn
> [PROD] [FAGSYSTEM-238338] kapitaliering av navn

- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforSak.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/SaksTabell.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/TemaTabell.tsx
- src/mock/journalforing/journalforing-mock.ts
- src/utils/date-utils.ts
feltet finnes ikke i responsen fra backend og vi endte derfor opp med å mangle dato for alle sakene i visningen
> [KAIZEN-0] sakstabell brukte feil felt for dato

- src/app/personside/dialogpanel/sendMelding/autofullforUtils.ts
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforSak.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/SaksTabell.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/TemaTabell.tsx
- src/mock/journalforing/journalforing-mock.ts
- src/utils/date-utils.ts
feltet finnes ikke i responsen fra backend og vi endte derfor opp med å mangle dato for alle sakene i visningen
> [PROD][KAIZEN-0] sakstabell brukte feil felt for dato

- src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/mock/standardTeksterMock.js
- src/utils/print/MeldingerPrintMarkup.tsx
- [KAIZEN-0] fikse standardtekster
- [KAIZEN-0] fikse keys for react-lister
- [KAIZEN-0] unngå sortering av tråd flere ganger for print-visning
- [KAIZEN-0] bygge in-memory tråd-index for søk
- [KAIZEN-0] memoisering av PrintAlleMeldinger
> [KAIZEN-0] fjerne console-støy og optimalisering av melding-søk

- src/app/PersonOppslagHandler/LyttPåNyttFnrIReduxOgHentAllPersoninfo.tsx
- src/app/personside/BegrensetTilgangSide.tsx
- src/app/personside/Personoversikt.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.test.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/fortsettDialog/useOpprettHenvendelse.tsx
- src/app/personside/infotabs/dyplenkeTest/sakerDyplenker.test.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/Sladdevalg.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AvsluttGosysOppgaveSkjema.tsx
- src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
- src/app/personside/infotabs/oversikt/SakerOversikt.tsx
- src/app/personside/infotabs/saksoversikt/SaksoversiktContainer.tsx
- src/app/personside/infotabs/saksoversikt/useSakstemaURLState.tsx
- src/components/person/BegrensetTilgangBegrunnelse.tsx
- src/components/popup-boxes/popup-boxes.tsx
- src/mock/tilgangskontroll-mock.ts
- src/rest/resources/dialogResource.tsx
- src/rest/resources/oppfolgingResource.tsx
- src/rest/resources/sakstemaResource.tsx
- src/rest/resources/tildelteoppgaverResource.tsx
- src/rest/resources/tilgangskontrollResource.tsx
- src/test/testStore.ts
- src/utils/hooks/useTildelteOppgaver.ts
react-query er mer brukt, aktivt forvaltet og støtter refetching mye mer elegant.
> [KAIZEN-0] bytte ut useFetch for react-query for sakstema

- Dockerfile
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/MeldIPortenAdvarsel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdMeldingerMedArsak.module.css
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdMeldingerMedArsak.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdTradMedArsak.tsx
Legger til samme alert om at sladding må meldes i porten som tidligere vist ved valg av årsak
> [PROD][OPP-1501] legge til melding om porten ved sladding

- src/api/api.ts
- src/app/FetchSessionInfoOgLeggIRedux.tsx
- src/app/personside/infotabs/saksoversikt/SaksDokumentIEgetVindu.tsx
- src/app/personside/infotabs/saksoversikt/dokumentvisning/DokumentOgVedlegg.tsx
- src/app/personside/infotabs/saksoversikt/dokumentvisning/SaksDokumentVisning.tsx
- src/rest/resources/oppgaveBehandlerResource.tsx
- dea235cc8 [KAIZEN-0] bruke fnr fra url
> [PROD] [KAIZEN-0] bruke fnr fra url

- src/app/personside/dialogpanel/sendMelding/standardTekster/velgTekst/TekstListeElement.tsx
- src/app/personside/infotabs/meldinger/traadliste/TraadListeElement.tsx
- src/app/personside/infotabs/meldinger/traadliste/__snapshots__/TraadListe.test.tsx.snap
- b28105382 [KAIZEN-0] gjøre labels synlig for skjermlesere igjen
> [PROD] [KAIZEN-0] gjøre labels synlig for skjermlesere igjen

- .nais/prod.yaml
- e82353208 [KAIZEN-0] skru på azuread innlogging
> [PROD] [KAIZEN-0] skru på azuread innlogging

- src/app/personside/infotabs/saksoversikt/dokumentvisning/SaksDokumentVisning.tsx
- abb581dcb [KAIZEN-0] hente dokument vha proxy
> [PROD] [KAIZEN-0] hente dokument vha proxy

- src/app/personside/dialogpanel/use-draft.ts
nettverksfeil skal ikke føre til at man forsøker å koble seg opp mot websocket med ugyldig uuid.
> [KAIZEN-0] legge til bedre feilhåndtering ved feil mot draft-appen

- .nais/prod.yaml
- .nais/qa-template.yaml
- Dockerfile
nytt host image som bruker sessionid-cookie  og postgresql som 2nd-tier cache
> [KAIZEN-0] bump host image

- src/app/personsok/PersonsokSkjema.tsx
- src/app/personsok/personsokUtils.ts
- src/mock/personsok/personsokMock.ts
- src/models/person/personsok.ts
legges til slik at vi kan se hvilke enheter som bruker kontonummer søket
> [KAIZEN-0] sende med valgt enhet ved personsok

- src/app/personside/infotabs/saksoversikt/saksdokumenter/JournalPostListeElement/JournalpostListeElement.tsx
- src/app/personside/infotabs/saksoversikt/saksdokumenter/JournalPoster.tsx
- src/app/personside/infotabs/saksoversikt/utils/saksoversiktUtils.ts
- src/mock/saksoversikt/aremark-saksoversikt-mock.ts
- src/mock/saksoversikt/behandlingskjeder-mock.ts
- src/mock/saksoversikt/journalpost-mock.ts
- src/mock/saksoversikt/saksoversikt-mock.ts
- src/models/saksoversikt/journalpost.ts
- src/models/saksoversikt/sak.ts
- src/models/saksoversikt/sakstema.ts
Ikke behov for V2 suffix etter endring i backend
> [KAIZEN-0] bytte tilbake til riktige variabelnavn

- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/components/autocomplete-textarea/autocomplete-textarea.tsx
- src/mock/standardTeksterMock.js
Har gått igjennom alle autocomplete tekstene som ligger i modia, og sjekket at de fortsatt returneres fra skrivestotte og det gjør de. Er det noe mer som må sjekkes i forhold til tekster som skal slettes?
> [OPP-1538] Fjerne corona tekster

- src/app/oppdateringslogg/config/config.tsx
- **[KAIZEN-0] Oppdater logg om journalføring**
> [KAIZEN-0] Oppdater logg om journalforing

- .nais/prod.yaml
- .nais/qa-template.yaml
Legge til `data:` i img-src igjen i preprod (den ble fjernet ved en feil).
Og oppdater prod CSP for å matche preprod.
> [KAIZEN-0] Oppdater CSP direktiver

- index.html
- src/app/internarbeidsflatedecorator/Decorator.tsx
- src/mock/context-mock.ts
- src/mock/index.ts
- src/mock/saksbehandlerinnstillinger-mock.ts
- src/window-variabler.ts
- **Sett applicationFeatureToggles i mock i dev**
- **Fikse flere BASE_URL feil**
Fjerner også appDynamics
> Mock featuretoggles lokalt & fikse et par base url feil

- src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap
- src/app/personside/visittkort-v2/header/status/PersonStatus.tsx
Robot teamet bruker html atributter for å hente ut data fra siden. Denne gjør det litt lettere.
> Legg til data-test-id på fnr for robot

- index.html
- src/app/internarbeidsflatedecorator/Decorator.tsx
- src/app/internarbeidsflatedecorator/decoratorprops.ts
- src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
- src/index.tsx
- src/mock/index.ts
- src/window-variabler.ts
Vi kjører V3 i prod nå og den fungerer uten feil
> Fjerne decorator v2

- .nais/prod.yaml
- proxy-config.json
- vite.config.ts
Data er migrert og alt ser :ok: ut :rocket:
> Bruk skrivestotte i GCP

- Dockerfile
- preprod-proxy-config.json
Nå skal servere som gjør routing på host headeren faktisk fungere med proxy og modialogin.
> [PROD] Fikse proxying i modialogin

- .nais/prod.yaml
- proxy-config.json
- src/app/personside/Personoversikt.tsx
- vite.config.ts
Reverts navikt/modiapersonoversikt#2177
> Revert "Revert "[PROD]""

- preprod-proxy-config.json
- proxy-config.json
Og bruk gcp innstillinger i prod
> Bruk gcp versjon av innstillinger og draft i dev

- src/app/personside/visittkort-v2/PersondataDomain.ts
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/fullmakt/Fullmakt.tsx
- src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap
- src/mock/persondata/aremark.ts
Ny format på data fra APIet, og det inkluderer nå handling per tema i
fullmakten.
> legg til handling per tema for fullmakter

- package-lock.json
- package.json
- src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap
- src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx
- src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
- src/app/personside/dialogpanel/use-draft.ts
- src/components/featureToggle/toggleIDs.ts
- src/index.tsx
- src/mock/featureToggle-mock.ts
- src/rest/resources/featuretogglesResource.tsx
Legger på statusen på draft, slik at brukere kan se om meldinger er lagret eller ikke.
> Legg til status på melding-utkast

- src/utils/observability.ts
Må testes om denne overskriver default page meta.
> Prøv å maskere fnr i url i faro

- src/utils/observability.ts
- **Prøv å maskere fnr i url i faro**
- **Legg på manglende global flag på replacement regex**
> Manglende regex global flag i faro replacement

- src/utils/observability.ts
Skal i teorien ignorere events med url som inneholder fnr
> Prøv å bruke ignoreUrls for å fjerne fnr

- src/app/personside/dialogpanel/DraftStatus.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
- src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx
- src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx
Den var kun lagt til på Ny melding, og ble glemt å i fortsett dialog...
> Legg til draft status på FortsettDialog også

- package-lock.json
- package.json
Og oppdater pakke for å fjerne vulnerability
> Fjern ikke nødvendig types pakke

- .env.development
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/ytelser/ValgtYtelse.tsx
- src/app/personside/infotabs/ytelser/YtelserListe.tsx
- src/app/personside/infotabs/ytelser/YtelserListeElement.tsx
- src/app/personside/infotabs/ytelser/__snapshots__/Ytelser.test.tsx.snap
- src/app/personside/infotabs/ytelser/tiltakspenger/Tiltakspenger.tsx
- src/app/personside/infotabs/ytelser/useBrukersYtelser.tsx
- src/components/featureToggle/toggleIDs.ts
- src/mock/featureToggle-mock.ts
- src/mock/index.ts
- src/mock/ytelse/statiskTiltakspengerMock.ts
- src/mock/ytelse/tiltakspenger-mock.ts
- src/models/ytelse/tiltakspenger.ts
- src/models/ytelse/ytelse-utils.ts
- src/rest/resources/tiltakspengerResource.tsx
- src/utils/string-utils.ts
Er gjemt bak feature toggle.
En del snapshots er oppdatert fordi jeg oppdaget at mocken ikke var helt riktig :sweat_smile:. Antakeligvis da jeg byttet til MSW.
> Vis tiltakspenger under ytelser

- src/app/Routing.tsx
- src/app/innkrevingskrav/Innkrevingskrav.ts
- src/app/innkrevingskrav/InnkrevingskravSide.tsx
- src/app/routes/routing.tsx
- src/mock/index.ts
- src/mock/innkrevingskrav.ts
- src/rest/resources/innkrevingsKravResource.ts
Veldig enkel side for initiell visning av kravdetaljer.
> [TPO-56] Initiell, enkel side for kravdetaljer

- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/fullmakt/Fullmakt.tsx
- src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap
> [TPO-69] Rydd opp i visning av fullmakttilganger

- src/app/innstillinger/modal/InnstillingerModalInnhold.tsx
- src/app/internarbeidsflatedecorator/personsokKnapp.less
- src/app/oppdateringslogg/config/config.tsx
- src/app/oppdateringslogg/oppdateringsloggKnapp.less
- src/rest/resources/innstillingerResource.tsx
For å passe med nytt design. I samme slengen fant jeg en bug i
innstillinger.
> Gjør knapper i dekoratør litt mindre

- src/app/PersonOppslagHandler/SetFnrIRedux.tsx
- src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts
Gosys lenker ikke til via redirect servicen, som ødelegger en del URLer
> Prøv å fiks race-condition med fnr & håndter gosys

- index.html
- proxy-config-dev.json
- src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
- src/components/featureToggle/toggleIDs.ts
Denne er nå i dev, og toggle trengs ikke lenger
> Fjern featureToggle for contextholderNext

- package-lock.json
- package.json
Reverts navikt/modiapersonoversikt#2339
> Revert "Bump react-day-picker from 7.4.10 to 9.1.4"

- package-lock.json
- package.json
- **Bump eslint fra 9.12 til 9.14**
- **Oppdater aksel fra 6.x til 7.x**
> Oppgrader litt pakker

- src/app/PersonOppslagHandler/SetFnrIRedux.tsx
- src/app/Routing.tsx
- src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
- src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts
- src/app/personside/infotabs/meldinger/traadvisning/TraadVisningWrapper.test.tsx
- src/context/valgtenhet-state.tsx
- src/routes/$.tsx
- src/routes/__root.tsx
- src/test/Testprovider.tsx
- src/utils/customHooks.ts
Fikse bruker resetting, navigasjonsproblemer og litt styling.
> Fikse litt redux/router + tanstack/jotai migrasjon

- src/utils/HandleLegacyUrls.tsx
Denne fetchen brukes ikke til noe annet enn logging, så vi fjerner den.
> Fiks RC ved url fra gosys med oppgaveid

- src/components/PersonSidebar.tsx
- src/routes/new/person/arbeid.lazy.tsx
- **Legg til sikkerhetsmodal i personlinje**
- **Legg til arbeid route**
> arbeid route

- src/app/innkrevingskrav/InnkrevingskravSide.tsx
- src/components/PersonLinje/Details/Fullmakt.tsx
- src/components/PersonLinje/Details/KontaktInfo/Adresse.tsx
- src/components/PersonLinje/Details/KontaktInfo/Bankkonto.tsx
- src/components/PersonLinje/Details/KontaktInfo/Dodsbo.tsx
- src/components/PersonLinje/Details/KontaktInfo/Epost.tsx
- src/components/PersonLinje/Details/KontaktInfo/KRRInfo.tsx
- src/components/PersonLinje/Details/KontaktInfo/NavKontaktinfo.tsx
- src/components/PersonLinje/Details/KontaktInfo/Telefon.tsx
- src/components/PersonLinje/Details/KontaktInfo/index.tsx
- src/components/PersonLinje/Details/components.tsx
- src/components/PersonLinje/Details/index.tsx
- src/components/PersonLinje/common/ValidPeriod.tsx
- src/components/PersonLinje/index.tsx
- src/components/PersonLinje/utils.ts
- src/generated/modiapersonoversikt-api.d.ts
- src/lib/types/modiapersonoversikt-api.d.ts
- src/utils/hooks/useClickAway.ts
https://github.com/user-attachments/assets/214402a7-be28-42e7-bcbb-bab8cb7c4dc3
> Personlinje: Kontaktinfo seksjon

- src/components/PersonLinje/Details/DeltBosted.tsx
- src/components/PersonLinje/Details/Familie/Sivilstand.tsx
- src/components/PersonLinje/Details/Familie/components.tsx
- src/components/PersonLinje/Details/ForeldreAnsvar.tsx
- src/components/PersonLinje/Details/Fullmakt.tsx
- src/components/PersonLinje/Details/KontaktInfo/Bankkonto.tsx
- src/components/PersonLinje/Details/NavKontor/index.tsx
- src/components/PersonLinje/Details/PdlLenke.tsx
- src/components/PersonLinje/Details/Sikkerhetstiltak.tsx
- src/components/PersonLinje/Details/TilrettelagtKommunikasjon.tsx
- src/components/PersonLinje/Details/Vergemal.tsx
- src/components/PersonLinje/Details/components.tsx
- src/components/PersonLinje/Details/index.tsx
- src/components/PersonLinje/Sikkerhetstiltak.tsx
- src/components/PersonLinje/common/ValidPeriod.tsx
- src/components/PersonLinje/index.tsx
- src/lib/clients/modiapersonoversikt-api.ts
- src/lib/types/modiapersonoversikt-api.d.ts
Og tweak litt på tekststørrelse og farger.
> Migrer siste elementer til ny personlinje

- index.html
- src/index.css
For å forhindre issues med spesifisitet, spesielt for globale styles fra
tailwind & reset.
> Importer all preflight styles i eget layer

- src/index.css
For å ikke ødelegge theme i header.
> Scope dark theme til ny modia container

- src/app/personside/infotabs/saksoversikt/saksdokumenter/DokumentLenke.tsx
- src/components/ObjectHttpFeilHandtering.tsx
Og fjerne ikke-fungerende last-ned knapp.
> Lenke for å laste ned dokument som ikke kan vises

- src/components/PersonLinje/index.tsx
- src/components/melding/LukkbarNyMelding.tsx
Og gjøre skeleton til personlinje samme høyde som personlinja
> Lagre state på meldingpanel i localStorage

- src/components/DateFilters/DatePeriodSelector.tsx
- src/components/DateFilters/PeriodDatePicker.tsx
- src/components/DateFilters/types.ts
- src/components/Meldinger/Detail/index.tsx
- src/components/Meldinger/List/Filter.tsx
- src/components/Meldinger/List/TraadItem.tsx
- src/components/Meldinger/List/index.tsx
- src/components/Meldinger/List/utils.ts
- src/components/Meldinger/index.tsx
- src/components/PaginatedList/index.tsx
- src/components/RichText/index.tsx
- src/components/RichText/styles.css
- src/lib/clients/modiapersonoversikt-api.ts
DateRange pickeren vår med radio buttons er også dratt ut i en ny
komponent og betydelig forenklet og refaktorert litt.
https://github.com/user-attachments/assets/2fa532f1-2f75-4476-af95-20eb0f8a4be6
> Filtrering på tråder/meldinger

- src/components/melding/FortsettDialog.tsx
- src/components/melding/nyMeldingSchema.ts
- src/components/melding/useHenvendelse.ts
- src/lib/clients/modiapersonoversikt-api.ts
Fortsatt ikke helt 100%, men nå _tror_ jeg det skal være på lik linje som før (med litt kinks).
Det trengs nok en jobb her fortsatt med å få denne flyten til å være bra, muligens og med noe endringer i hvordan vi henter og assosierer oppgaver i backenden.
> Oppgavehåndtering for fortsett dialog

- src/components/ErrorBoundary.tsx
- src/components/Meldinger/Detail/index.tsx
- src/components/Meldinger/List/index.tsx
- src/components/QueryErrorBoundary.tsx
- src/components/melding/SendMelding.tsx
- src/components/personsok/form/index.tsx
Bruk komponent for rendring av FetchErrors og pass på at alle suspense
queries har suspense boundary og error boundary.
> Rydde opp i error handling

- .github/workflows/ci.yml
- eslint.config.js
- knip.jsonc
- package.json
- pnpm-lock.yaml
- reactCompiler.js
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/saksdokumenter/JournalPosterV2.tsx
- src/components/MediaQueryAwareRenderer.tsx
- src/components/Meldinger/List/Filter.tsx
- src/components/Meldinger/List/TraadItem.tsx
- src/components/autocomplete-textarea/autocomplete-textarea.tsx
- src/components/form/FormSelect.tsx
- src/components/form/FormTextArea.tsx
- src/components/form/formUtils.ts
- src/components/melding/LukkbarNyMelding.tsx
- src/lib/types/temagruppe.ts
- src/utils/HandleLegacyUrls.tsx
- src/utils/customHooks.ts
- src/utils/hooks/use-hotkey.ts
- vite.config.ts
- **Legg til og skru på react-compiler og eslint rule**
- **Fikse react compiler errors**
> React compiler

- src/components/Meldinger/List/TraadItem.tsx
- src/components/Meldinger/index.tsx
- src/components/PaginatedList/index.tsx
- src/components/PersonLinje/Badges.tsx
- src/components/PersonLinje/Details/components.tsx
- src/components/PersonLinje/index.tsx
- src/components/PersonSidebar.tsx
- src/components/melding/SendMelding.tsx
Heading nivåer, manglende sections og litt sematikk.
> Rydd opp i tilgjengelighet

- e2e/meldinger.spec.ts
- reactCompiler.js
- src/components/Meldinger/Detail/index.tsx
- src/components/Meldinger/Oppgave.tsx
- src/generated/modiapersonoversikt-api.ts
- src/lib/clients/modiapersonoversikt-api.ts
- src/mock/getSaksBehandlersEnheterMock.ts
- src/mock/index.ts
- src/mock/innloggetSaksbehandler-mock.ts
- src/mock/meldinger/oppgave-mock.ts
- src/mock/mockBackend/oppgaverBackendMock.ts
Skal fungere likt som den  gamle :tm:
> Nytt oppgaveskjema

- src/components/Meldinger/AvsluttOppgave.tsx
- src/components/Meldinger/Detail/index.tsx
- src/components/Meldinger/List/utils.ts
- src/components/melding/AvsluttDialogEtterSending.tsx
- src/components/melding/LukkbarNyMelding.tsx
- src/components/melding/NyMelding.tsx
- src/components/melding/TildelteOppgaver.tsx
- src/components/melding/UbesvarteMeldinger.tsx
- src/components/melding/VelgTema.tsx
- src/lib/clients/modiapersonoversikt-api.ts
- src/mock/dialoger/sf-dialoger-mock.ts
- src/mock/index.ts
- src/mock/mockBackend/oppgaverBackendMock.ts
- Lik funksjon for å vise tildelte oppgaver på bruker som før.
- Knapp for å avslutte oppgave (med skjema i modal) for oppgaver på
tråder.
- Varsel for ubesvarte henvendelser fra bruker
> Tildelte oppgaver varsel/avslutt oppgave/ubesvarte

- src/app/personside/infotabs/oversikt/SakerOversiktV2.tsx
- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/saksoversikt/dokumentvisning/DokumentOgVedleggV2.tsx
- src/app/personside/infotabs/saksoversikt/sakstemaliste/SakstemaListeElementCheckboksV2.tsx
- src/app/personside/infotabs/saksoversikt/sakstemaliste/SakstemaListeElementKnappV2.tsx
- src/app/personside/infotabs/saksoversikt/sakstemaliste/SakstemaListeUtils.tsx
- src/app/personside/infotabs/saksoversikt/useSakstemaURLState.tsx
- src/app/personside/infotabs/saksoversikt/utils/saksoversiktUtilsV2.ts
- src/mock/saksoversikt/aremark-saksoversikt-mockV2.ts
- src/mock/saksoversikt/saksoversikt-mock.ts
- src/mock/saksoversikt/soknadsstatus-mock.ts
- src/models/saksoversikt/sakstema.ts
- src/rest/resources/sakstemaResource.tsx
Reverts navikt/modiapersonoversikt#2927
> Revert "[KAIZEN-0] Fjernet sokand status data i sakstema responsen."

- src/components/Utbetaling/Detail/index.tsx
- src/components/Utbetaling/List/index.tsx
- src/components/Utbetaling/index.tsx
- src/components/varsler/List/index.tsx
La til infoboks når filteringen resulterer i 0 resultat for utbetalinger og for varsler då det mangla der.
jira: https://jira.adeo.no/browse/TPO-112
> Info ved ingen resultat

- package.json
- pnpm-lock.yaml
- src/app/personside/infotabs/oppfolging/__snapshots__/OppfolgingContainer.test.tsx.snap
- src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap
- src/app/personside/infotabs/ytelser/__snapshots__/Ytelser.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap
- src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap
- src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap
+ oppdatering av snapshottestene.
Denne oppdateringen av ds-react er nødvendig for at akselkomponenten skal fungere
> Bump @navikt/ds-react from 7.22.0 to 7.23.1 

- index.html
- src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
- src/utils/analytics.ts
Reverts navikt/modiapersonoversikt#3078
Det skjer ein feil når ei klikkar på lenker i meyen pga no referer
> Revert "Non blocking umami"

- src/app/personside/Personoversikt.tsx
- src/components/featureToggle/toggleIDs.ts
- src/rest/resources/tilgangskontrollResource.tsx
- src/test/testStore.ts
jira: https://jira.adeo.no/browse/TPO-128
Feature toggle for tilgangsmaskin. Planen er gradvis rollout på denne.
> Feature toggle for tilgangsmaskin

- src/components/featureToggle/toggleIDs.ts
- src/mock/featureToggle-mock.ts
- src/test/testStore.ts
Ingen av desse blei brukt nokon plass.
Skal slette i Unleash når koden er ute.
> Arkiver feature toggles

- e2e/meldinger.spec.ts
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/BegrensetTilgang/OppgaveSkjemaBegrensetTilgang.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjema.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OpprettOppgaveContainer.tsx
- src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/oppgaveInterfaces.ts
- src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
- src/components/Meldinger/List/utils.ts
- src/components/Meldinger/MeldingerPrint.tsx
- src/components/Meldinger/Merk.tsx
- src/mock/meldinger/meldinger-mock.ts
- src/models/meldinger/meldinger.ts
- src/utils/print/MeldingerPrintMarkup.tsx
Kontorsperre vil bli fjerna frå henvendelse-API
> Fjern all referanse til kontorsperre

- .nais/dev.yaml
- .nais/prod.yaml
- Dockerfile
Oppdater modia frontend og legg til nais logging i outbound policy
> Logs frå modia-frontend til team logs

- .nais/dev.yaml
- .nais/prod.yaml
- Dockerfile
Reverts navikt/modiapersonoversikt#3188
> Revert "Legg til nye modia frontend med pino logger"

- .nais/dev.yaml
- .nais/prod.yaml
- Dockerfile
Reverts navikt/modiapersonoversikt#3192
> Revert "Revert "Legg til nye modia frontend med pino logger""

- src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
- src/app/personside/infotabs/ytelser/__snapshots__/Ytelser.test.tsx.snap
- src/app/personside/infotabs/ytelser/useBrukersYtelser.tsx
Reverts navikt/modiapersonoversikt#3193
> Revert "[KAIZEN-0] disable pensjon"
