navikt/modiapersonoversikt

package-lock.json, package.json, public/.gitignore, src/index/dev/index.html, src/index/prod/index.html
Istedenfor å ejecte fra create-react-script setter vi opp to versjoner
av index.html som kopieres inn i public mappen. En dev versjon referer
til navigasjonsmenyen på Github pages, mens den for prod refererer til
en relativt i miljø. Det kopieres inn før build eller npm start blir
kjørt.
=> Oppsett for lokal utvikling for navigasjonsmeny

src/stories/grid-layout/GridLayout.tsx, src/stories/grid-layout/gridStyle.css, src/stories/index.stories.tsx
nicklas vil gjerne at vi tar ibruk css-grid i personoversikten. Her er en story med grid-layout, men den funker desverre ikke i ie11 slik den er nå. Ta gjerne tak i det hvis noen føler seg inspirert ;-)
chrome:
ie11:
=> gridlayout i stroybook

src/mock/setup-mock.ts, src/mock/utils.ts
Gjør det enklere å teste hvordan det blir hvis et rest-kall skulle feile.
=> Refaktorer mock-setup til å tillate å enkelt konfigurere opp at et endepunkt skal feile

src/mock/utils/fnr-utils.ts
Noen ganger kan kontrollsiffer bli 10 og da blir det veldig feil. Wikipedia sier at disse fnr'ene skal forkastes. Men vi kan ikke lage en helt nye fnr-genereringslogikk med sjekking på evige løkker osv... Bare for mocking. Så i stdet for å forkaste så bare returnerer vi aremark. Får heller bli feil innimellom.
=> Ekstra sikkerhet på langde fnr

src/utils/endretAvUtil.test.ts, src/utils/endretAvUtil.ts
I tilegg lagt støtte for eldre typer identer i NAV som hadde 3 bokstaver og 4 tall.
OPP-396
=> Lagt til diffrensiering i endretAv-metode for Folkeregisteret vs Skatt

src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort/header/__snapshots__/VisittkortHeader.test.tsx.snap, src/components/person/NavnOgAlder.test.tsx, src/components/person/NavnOgAlder.tsx, src/mock/kontaktinformasjon-mock.ts, src/mock/person/aremark.ts, src/models/person/person.ts
Det viser seg at navn på familierelasjoner noen ganger har null satt til
fornavn og etternavn, men at de har et sammensatt navn. Innfører derfor
sjekker på det for å unngå navn som (null null).
=> Håndtering av null på fornavn og etternavn for familierelasjoner

app-config.yaml, entrypoint.sh
Requester til backend går til /modiabrukerdialog, da de kjører på samme
domene.
Det er derfor ikke _nødvendig_  å konsumere denne fasit-variablen. Vi
beholder imidlertidig muligheten for å sette den, slik at vi i f.eks kan
kjøre på heroku mot en backend på et annet domene.
=> Fjerner bruk av miljøvariabler på nais.

src/app/personside/visittkort/body/familie/Sivilstand.tsx
Eksempelvis når personen som er slått opp er død. Viser ikke datoen dersom den er satt til denne merkelige nulldatoen.
=> TPS sender en merkelig nulldato i noen tilfeller

src/app/personside/visittkort/body/kontaktinformasjon/NavKontaktinformasjon.tsx, src/mock/kodeverk/retningsnummer-mock.ts, src/mock/person/aremark.ts, src/mock/person/navKontaktinformasjon.ts, src/mock/setup-mock.ts
Skyldes at koderefen for et retningsnummer allerede inneholder et
plusstegn.
=> Fiks feil der det ble vist to plusstegn foran retningsnummere

app.json
Da skjønner forhåpentligvis heroku at den må hente det fra
'master'-appen
=> Spesifiser at miljøvariabel er påkrevd

package-lock.json, package.json, src/app/App.tsx, src/app/Eventlistener.tsx, src/app/personside/PersonsideContainer.tsx, src/app/personside/dialogpanel/DialogPanel.tsx, src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/routes/routing.tsx, src/app/startbilde/Startbilde.tsx, src/redux/oppgaver.ts, src/redux/reducer.ts, src/redux/restReducer.ts, src/redux/utils.ts
Flytter litt på logikken rundt routing. Lager en Eventlistener-komponent
på toppnivå som er ansvarlig for å reagere på events fra
navigasjonsmenyen. Videre brukes history fra react-router til å
pushe/endre URLen. Dette blir brukt for å holde styr på hvilken person
som er søkt opp.
=> Fjern react-router-redux - den er deprecated

src/app/personside/visittkort/body/VisittkortElement.tsx, src/components/EtikettMini.tsx
I testene, pluss i gamle modiabrukerdialog med nytt visittkort, fikk vi
denne feilen:
Error: Element type is invalid: expected a string (for built-in
components) or a class/function (for composite components) but got:
undefined. You likely forgot to export your component from the file it's
defined in, or you might have mixed up default and named imports.
Løste seg i test ved å spesifisere importen mer nøyaktig
=> Fiks feil forårsaket av lite eksplisitt import

src/app/brukerprofil/kontonummer/EndreKontonummerForm.tsx, src/app/brukerprofil/kontonummer/UtenlandskKontonummerInputs.tsx, src/app/brukerprofil/kontonummer/norskKontoValidator.ts, src/redux/reducer.ts
feil fra tavla:
* retter skrivefeil
* formen tømmes når man bytter mellom norsk/utenlandsk kontonummer
* tom streng er nå akseptert som kontonummer. Det vil si å sette brukers kontonummer til "ikke registrert"
=> Kontonr fra tavla

src/components/standalone/VisittKort.tsx
Dette førte til en feil med reloading-funksjonaliten som førte til
undefined person. Årsaksforløp:
personreducer -> Loading
personreducer -> Reloading (uten at det første kallet gikk igjen)
Innholdslasteren venter ikke på reloading noe som førte til umiddelbar
rendring av personinformasjon som aldri var blitt loadet. Og da kræasjet
det.
=> Fiks feil der vi dispatchet henter person to ganger

src/redux/restReducers/restReducer.ts
Ikke sett reloading hvis reducer-staten er loading. Loading må fullføres
for å sikre at man har data i reduceren.
=> Feilfiks restreducer ved reloading

src/app/personside/visittkort/body/familie/Foreldre.tsx, src/app/personside/visittkort/body/familie/ListeAvBarn.tsx, src/app/personside/visittkort/body/familie/Sivilstand.tsx, src/app/personside/visittkort/body/familie/common/Diskresjonskode.tsx
* Diskresjonskodelablen, som rendres som en div, kan ikke være inne i en
undertekst.
* Fødselsnummer er null/undefined hvis familerelasjonen har
diskresjonskode
=> Støtter at familierelasjoner har litt manglende data pga. diskresjonskode

src/app/App.tsx, src/app/AppWrapper.ts, src/app/brukerprofil/BrukerprofilSide.tsx, src/app/personside/MainLayoutStyles.tsx, src/app/personside/dialogpanel/DialogPanel.tsx, src/app/personside/infotabs/TabKnapper.tsx, src/app/personside/visittkort/Visittkort.test.tsx, src/app/personside/visittkort/VisittkortContainer.tsx, src/app/startbilde/StartBildeLayout.ts, src/components/FillCenterAndFadeIn.ts, src/components/pilknapp.tsx, src/components/standalone/HentOppgaveKnapp.tsx, src/components/standalone/VisittKort.tsx, src/styles/personOversiktStyles.ts, src/styles/personOversiktTheme.ts, src/test/Testprovider.tsx
ble ikke brukt. Globale stiler kan nå hentes fra javascript-objekt i personOversiktStyles istedenfor. Skaper mer lesbar kode og bedre autocomplete
=> skriver vekk ThemeProvider fra styled-components

src/app/personside/infotabs/InfoTabs.test.ts, src/app/personside/infotabs/InfoTabs.tsx
valgt tab håndteres nå i router istedenfor state
er ikke dreven på react router, og synes dette egentlig ble litt uryddig. Tar gjerne feedback på hvordan dette kan løses bedre. Spesielt er det metoden getOpenTabFromUrl() jeg er usikker på.
https://github.com/navikt/modiapersonoversikt/blob/1eb6554241c6862483f054c88ae86cac9b413811/src/app/personside/infotabs/InfoTabs.tsx
=> legger til react-router i infotabs

src/app/personside/visittkort/ShortcutListener.tsx
OPP-539 
Alt+N (og Alt+B) hurtigtastene fungerte ikke i IE.
=> event.code er ikke støtte i IE, tar i bruk .key istedet

src/app/personside/infotabs/utbetalinger/HandleUtbetalingerArrowKeys.tsx, src/app/personside/infotabs/utbetalinger/HandleUtbetalingerHotKeys.tsx, src/app/personside/infotabs/utbetalinger/MånedsGruppe.tsx, src/app/personside/infotabs/utbetalinger/Utbetalinger.tsx, src/app/personside/infotabs/utbetalinger/UtbetalingerContainer.tsx, src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap, src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetalt.tsx, src/app/personside/infotabs/utbetalinger/utbetaling/DelUtbetaling.tsx, src/app/personside/infotabs/utbetalinger/utbetaling/EnkelUtbetaling.tsx, src/app/personside/infotabs/utbetalinger/utbetaling/SammensattUtbetaling.tsx, src/app/personside/infotabs/utbetalinger/utbetaling/Utbetaling.tsx, src/app/personside/infotabs/utbetalinger/utils/CommonStyling.tsx, src/redux/reducers.ts, src/redux/utbetalinger/utbetalingerStateReducer.ts
Prøver å fikse rapportert heng og treghet i nye utbetalinger ved å ta i bruk redux og PureComponent for å sørge for færre re-renders. Dette ga ganske stor ytelsesforbedring.
=> Pil navigerings fiks

nginx.conf
da slipper man å skrive `/modiapersonoversikt/` manuelt i adressefeltet
=> fikser heroku url slik at man kommer rett inn i appen når man trykker "View Deployment"

src/app/personside/infotabs/TabKnapper.tsx, src/app/personside/infotabs/ytelser/YtelserContainer.tsx, src/app/personside/infotabs/ytelser/pleiepenger/Oversikt.tsx, src/app/personside/infotabs/ytelser/pleiepenger/Pleiepenger.tsx, src/app/personside/infotabs/ytelser/pleiepenger/PleiepengerEkspanderbartPanel.tsx, src/app/personside/infotabs/ytelser/pleiepenger/Pleiepengerperiode.tsx, src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap, src/app/personside/infotabs/ytelser/pleiepenger/pleiepengerUtils.test.tsx, src/app/personside/infotabs/ytelser/pleiepenger/pleiepengerUtils.ts, src/components/common-styled-components.tsx, src/components/standalone/Pleiepenger/PleiepengerLaster.tsx
* Begrenser bredden på pleiepengersiden slik at den ikke blir for bred og uleselig
* fjerner pleiepengedager som ikke er relevant lenger
* lenken "vis alle arbeidsforhold" skjules dersom det ikke er mer enn ett arbeidsforhold
* fikser teknisk feil som skjedde dersom det ikke finnes vedtak for rettigheten
=> Pleiepenger fixes

src/app/personside/kontrollsporsmal/HandleKontrollSporsmalHotkeys.tsx, src/app/personside/kontrollsporsmal/Header.tsx, src/redux/kontrollSporsmal/actions.ts, src/redux/kontrollSporsmal/kontrollSporsmalReducer.test.ts, src/redux/kontrollSporsmal/reducer.ts, src/redux/kontrollSporsmal/types.ts
Dette var aldri en del av funksjonsbeskrivelsen, og ga egentlig forvirrende resultat da man ikke kunne toggle på igjen hvis funksjonalitet fungerte som det skulle, men plutselig kunne det pga EventListener buggen
=> Erstatter toggle funksjonalitet med kun lukking

src/api/utbetaling-api.ts, src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap, src/app/personside/infotabs/utbetalinger/filter/Filter.tsx, src/app/personside/infotabs/utbetalinger/totalt utbetalt/TotaltUtbetalt.tsx
For å fange opp utbetalinger frem i tid vil det ved valg av "SISTE 30 DAGER" og "INNEVÆRENDE ÅR" bli søkt også 100 dager fremover i tid.
I frontenden ønsker vi ikke å vise dette i periode-visningen da det kan være forvirrende å se en dato 100 dager frem i tid.
Legger derfor til logikk som vil vise dagens dato dersom sluttdato er frem i tid.
Legger også til begrensninger og feilmeldinger på datovalg slik at man ikke kan velge datoer frem i tid eller mer enn fem år tilbake i tid fom 1 januar da betalinger lenger tilbake i tid ikke er tilgjengelig fra tjenesten.
=> OPP-723 Visning av dato i totalt utbetalt og begrensninger på datovelger

src/mock/ytelse/statiskSykepengerMock.ts, src/mock/ytelse/sykepenger-mock.ts, src/mock/ytelse/ytelse-utbetalinger-mock.ts, src/models/ytelse/sykepenger.ts, src/models/ytelse/ytelse-utbetalinger.ts
Dette er ikke lenger i bruk, historiske utbetalinger hentes nå fra UR, og bruker samme interface som utbetaling
=> fjerner historiske utbetalinger. 

src/app/personside/dialogpanel/fortsettDialog/__snapshots__/FortsettDialog.test.tsx.snap, src/app/personside/infotabs/meldinger/traadvisning/Enkeltmelding.tsx, src/app/personside/infotabs/meldinger/traadvisning/enkeltmelding.less
svg'ene blir pr nå ikke med i biblioteket, dette førte til at bygget til modiabrukerdialog krasjet pga at den prøvde å trekke inn svg fra en js-fil
nå trekker vi svg inn via less istedenfor, less blir ikke pakket med i biblioteket heller og derfor prøver aldri modiabrukerdialog å trekke inn svg'en
komponenten som benytter svg brukes ikke i modiabrukerdialog, løser det derfor på denne måten, litt hacky, men hele problemstillingen forsvinner snart når vi lanserer nye personoversikten
=> trekker inn svg-er fra less for å unngå problem i modiabrukerdialog

src/app/personside/infotabs/meldinger/MeldingerContainer.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx, src/mock/meldinger/meldinger-mock.ts
Velger å legge inn en melding til brukeren om at tråden er journalfort fordi jeg synes det gir en bedre tilbakemelding og forståelse. Å kun disable knappen kan skape forvirring ettersom de ikke får vite hvorfor den er disablet.
=> [OPP-954] Infomelding dersom alle meldinger er journalfort

src/app/personside/dialogpanel/fortsettDialog/useOpprettHenvendelse.tsx
når man oppretter en ny henvendelse på en tråd vil backenden sjekke om
det finnes en oppgave på tråden. Hvis det finnes vil saksbehandler bli
tildelt oppgaven når man trykker "Ny melding" (eller egnetlig når ny
henvendelse blir opprettet). For at oppgaven skal bli
ferdigstilt når man til slutt svarer på meldingen må frontenden sende med
oppgaveId, og for å få tilgang på den må tildelte oppgaver refetches da
det er der oppgaveId ligger.
=> refetcher tildelte oppgaver etter at henvendelse er opprettet

src/app/personside/Personside.tsx, src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx, src/app/personside/visittkort/VisittkortContainer.tsx, src/components/featureToggle/toggleIDs.ts, src/mock/featureToggle-mock.ts
Kan godt ta en demo og en diskusjon på denne
commit-melding:
fjerner spinner som skjuler appen intill personinfo er lastet
pr nå vises en stor spinner på hele skjermen intill personinfo er ferdig lastet. Dette er egentlig en kunstig begrensning da vi helt fint kan vise mye annen informasjon før personinfo er ferdig lastet. Det betyr at saksbehandlere med denne endringen mye raskere kan komme igang med å scanne informasjon når vi ikke lenger trenger å vente på at dette ene rest-kallet er ferdig før appen kan vise noe av verdi.
Fikser samtidig duplikat kall mot personinfo
=> Forslag til hvordan vi raskere kan gi saksbehandlere info om bruker

src/app/personside/infotabs/meldinger/traadliste/TraadListe.tsx, src/utils/hooks/usePaginering.tsx
det kan være man blir sendt til personoversikten med lenke til en melding som ikke er på første side i paginering. Dette kan også skje dersom man er tildelt en oppgave tilknyttet en melding som ikke er på første side. Da må vi vise riktig side i paginering så det ikke blir forvirring rundt hvor meldingen ligger.
Denne løsningen vil i prakis alltid slå opp på riktig side on mount, så da vil navigering internt i appen også funke fint. Det vil også bli slått opp på riktig hvis valgt melding/selected Item settes programatisk.
=> paginering meldinger, sørger for å vise riktig side on mount

src/app/personside/dialogpanel/sendMelding/SendNyMeldingKvittering.tsx
Tilbakemelding fra pilotgruppe. Forvirrende tekst på kvittering til samtalereferat. Ordlyder som ikke er brukt tidligere
=> endre forvirrende kvitteringstekst

src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx, src/models/meldinger/meldinger.ts
Det går ann å journalføre på generelle saker uten saksId. Da opprettes
en ny sak (med saksId) på sakstema som er valgt. For å støtte dette må
hele saksobjektet sendes med i request, ikke bare saksId som er null for
saker som enda ikke er opprettet.
Kan ikke merges før denne er prodsatt: https://github.com/navikt/modiabrukerdialog/pull/218
=> OPP-1009 sender med hele saks-objektet for å støtte saker uten saksID

src/redux/restReducers/navkontor.ts, src/rest/utils/utils.ts
Greier ikke gjennskape dette lokalt. Kan virke som at det er noen race conditions som fører til at dette slår ut for denne ene brukeren. Ønsker derfor å dytte ut denne fiksen i prod for å se om situasjonen bedrer seg for bruker.
Tror dette er en feil med hvordan vi har fetchet navkontor. Navkontor er avhengig av geografisk tilknhytning som ligger i personinfo-objektet, men her har det blitt fetchet før personinfo-objektet er ferdig, noe som har ført til at navkontor har blitt fetchet med tom string som enhet. Da har backenden returnet "Not Found" og vi viser ingen enhet til bruker. Legger derfor til mulighet for å "escape" et fetch-kall ved å sende inn tom string som fetch-url.
=> OPP-1017 Saksbehandler får "ingen enhet" på alle brukere

src/app/personside/dialogpanel/HentOppgaveKnapp.tsx
viser ingen info-melding til de som ikke har rolle for plukk etter
tilbakemelding på at dette ikke skal vises da det kan være forvirrende
for lokal-kontor som ikke har noe forhold til denne rollen
=> viser feilmelindg istedenfor evig spinner dersom roller-fetchkall feiler

src/components/tekstomrade/parser/rules.ts
Pga innmeldt sak der lenke i standardtekst gjorde at saksbehandler
mistet tidligere skrevet data da lenken ble klikket.
Endringer pavirker ogsa visning av lenker i meldinger-lamellen,
slik at disse ogsa apnes i egen fane na
=> [KAIZEN-0] lenker i fritekst apnes i ny fane

src/app/personside/infotabs/oversikt/YtelserOversikt.tsx, src/app/personside/infotabs/oversikt/__snapshots__/Oversikt.test.tsx.snap
Fikser dette ønsket (tror jeg, vi må be brukerne følge litt ektra med i starten):
=> innformajson om variget på siste sykmelding på oversikten

src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx, src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap, src/mock/meldinger/meldinger-mock.ts, src/models/meldinger/meldinger.ts
riktig dato blir ikke hentet ut fra backend, ligger en PR i brukerdialog (https://github.com/navikt/modiabrukerdialog/pull/228/files) som må prodsettes før vi kan få ut riktig dato her. idag brukes ferdigstilltDato, som er feil og kan skape forvirring for brukeren.
=> Oppdatere avsluttetUtenSvar dato

src/app/personside/dialogpanel/ReflowBoundry.tsx, src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
Chrome greier ikke å finne en reflow/repaint boundry når det skjer endringer i tekstfeltet for samtalereferat etc. Dette skjer også om man erstatter dagens textarea med ett plain-old-textarea fra html. 
Man kan komme unna problemet med å endre på layout-mekanismen brukt i appen, e.g gå bort fra flexbox som primær-mekanisme for layout. Dette er nok noe som uansett burde vurderes da flexbox ikke er det beste alternativet for styring av layout. Css-grid er etter alt å dømme bra nok støttet i dagens browser-landskap til at dette sannsynligvis er en bedre approach fremover. 
For nå oppretter vi en "kunstig" reflow-boundry ved å absolutt-posisjonere elementene i dialogpanelet slik at vi slipper en reflow/repaint av hele siden når det er få elementer som endrer seg.
Enkelt tastetrykk i …
=> [KAIZEN-0] fikser issue med repaint av hele appen ved inntasting av tekst

src/rest/utils/utils.ts
Ref: https://nav-it.slack.com/archives/C8MU0M6L8/p1584528290011900
Bare et forslag, denne lager jo fort 25+ innslag av metrikker hver gang man slår opp en person. Fetch-metrikker logges vel nå uansett automatisk av nais nå når dere er over på ny backend?
=> ikke logge fetch-metrikker da det er mye last på influx-db for tiden

src/components/autocomplete-textarea/autocomplete-textarea.tsx
Bestilling;
```
Per nå har vi disse to ønskene: 
Familie - Omsorgspenger - Korona stengt bhg/skole
Tekst-id: 056be54e-d93d-487c-a6c2-238c885bdfd8
Ønsket titte/overskrift: OMS - Korona stengt bhg/skole
Ønsket hotkey: koroms
Familie - Overgangsstønad - Korona aktivitet STO
Tekst-id: 788b0492-a5e8-4883-a6af-6387ff1e46d6
Ønsket tittel/overskrift: OS - Korona aktivitet STO
Ønsket hotkey: korosakt
```
=> [KAIZEN-0] nye korona-hotkeys etter bestilling via teams-kanal

src/components/autocomplete-textarea/autocomplete-textarea.tsx
Kan legge til tekster på følgende måte; 
```
{
type: 'external',
regex: /^korosakt$/i,
externalId: '788b0492-a5e8-4883-a6af-6387ff1e46d6',
locale: Locale.en_US
}
```
Om `locale` ikke er satt brukes `Locale.nb_NO` som default verdi
=> [KAIZEN-0] la til locale-støtte for external-hotkey-tekster

src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/fortsettDialog/leggTilbakePanel/LeggTilbakepanel.tsx, src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts, src/models/Temagrupper.ts, src/models/oppgave.ts
Støtte slik at når henvendelse blir lagt tilbake kan også henvendelsen skifte temagruppe, no er det kun oppgave som gjer dette. Forberedelse til økonomisk sosialhjelp. legger til temagruppe økonomisk sosialhjelp på tilbakeleggbare temagrupper.
=> Opp 1116 temaskifte

src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx, src/app/personside/dialogpanel/fortsettDialog/leggTilbakePanel/LeggTilbakepanel.tsx, src/mock/featureToggle-mock.ts
* Ikke vis saks-velger på oppfølgingsspørmål når temagruppe er OKSOS,
siden disse ikke kan journalføres
* Fjern OKSOS som valg når man skal legge-tilbake og bruker har kode6
=> [OPP-1116] endringer ved introduksjon av oksos

package-lock.json, package.json, src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap, src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/__snapshots__/OpprettOppgaveContainer.test.tsx.snap
aria-describedby som referer til ett HTMLElement som endres på (id og
innhold) førte til at teksten ble lest opp av NVDA/JAWS.
Løst av https://github.com/navikt/nav-frontend-moduler/pull/736
=> [OPP-1177] bump nav-frontend-skjema

package-lock.json, package.json, src/setupTests.ts
Gjøres pga følgende issues;
https://github.com/github/fetch/issues/750
https://github.com/github/fetch/issues/748
https://github.com/zloirock/core-js/issues/751
https://github.com/zloirock/core-js/issues/741
I bunn og grunn, core-js@^3.6.0 introduserte støtte for
String.prototype.split med regex som har sticky-flag. Pga bug her så
fungerer ikke funksjonen som forventet noe mer i eldre IE11 versjoner.
E.g `"test".split(/e/) === ['t', 'e', 's', 't']`, denne burde gitt
`['t', 'st']`
=> [KAIZEN-0] tvinger core-js til versjon 3.5.0

package-lock.json, package.json, src/mock/context-mock.ts, src/mock/draft-mock.ts, src/mock/index.ts, src/mock/saksbehandlerinnstillinger-mock.ts, src/mock/utils.ts, src/mock/utils/failureMiddleware.ts, src/mock/utils/fetch-utils.ts
Tester ut oppgrader yet-another-fetch-mock bibliotek med enklere api.
Mock-funksjonen var tidligere definert og brukt sånn;
```
export type MockHandler =
| ((args: HandlerArgument) => Promise<ResponseData>)
| ((args: HandlerArgument) => JSONValue)
| JSONValue;
mock.get('url', () => ResponseUtils.jsonPromise(myJsonObject));
mock.get('url', () => myJsonObject);
mock.get('url', myJsonObject);
```
Behovet for å støtte de ulike måtene å skrive det på er erstattet med dette api-et;
```
export type Handler = (
req: HandlerRequest,
res: HandlerResponse,
ctx: HandlerContext
) => Promise<ResponseData>;
mock.get('url', (req, res, ctx) =>res(
ctx.json(myJsonObject)
));
``` 
Dette er sterkt inspirert fra https://redd.gitbook.io/msw/tutorials/mocking-rest-api (eksempel ca midt på siden), og gir i …
=> [KAIZEN-0] tester ut beta-versjon av yet-another-fetch-mock sitt nye api

.eslintrc.js, package.json
la samtidig inn `npm run lint` muligheten slik at man kan
verifisere om det er noen linting issues uten å starte appen.
Så det i en [PR](https://github.com/navikt/modiapersonoversikt/pull/1276/files#diff-3591d053393f239687b10af6c3bc3bb2R76) og stusset over at eslint ikke hadde reagert på det. 
Så er bare ett forslag på om vi ønsker enforcement av curly-braces i koden da vi per i dag alltid har curly-braces i koden ellers.
Lintingen generelt rapporterer bare noen urelaterte warning (:clap:) når jeg kjørte den med denne kodeendringen.
Discuss.
=> [KAIZEN-0] la til eslint-curly for konsistent kodestil

package-lock.json, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
Noen merk-operasjoner (se `DialogMerkController`) ferdigstiller oppgave
i gsak. Når det gjøres er det greit å nullstille oppgaven i frontend
også.
Men majoriteten av operasjonene der gjør ingenting med oppgaven, og det
skaper derfor hodebry for brukerene at de må relaste siden for å få
kvittert ut oppgaven etter en merk-operasjon
=> [OPP-1147] hindre resetting av oppgaveId for visse merk-operasjoner

src/app/personside/Personoversikt.tsx
flagget `fraGosys` blir kun satt i oppgavene når oppgaven blir håndtert
av `useHandleGosysUrl`. I disse tilfellene setter vi ikke `jobberMedSTO`
til `true` siden saksbehandler ikke har plukket en oppgave i dette
tilfellet.
=> [KAIZEN-0] utvide sjekk for når jobberMedSTO blir satt

src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/sendMelding/DialogpanelVelgSak.tsx, src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforSak.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx, src/app/personside/journalforings-use-fetch-utils.ts
ved journalføring, enten via sending av spørsmål eller
journalføringspanel, så kan en sak bli opprettet. I disse tilfellene vil
frontend ikke være oppdatert, og ved neste journalføring vil backend
derfor prøve å opprette saken på nytt. Ved å slette cachen av
sammensatte saker så kan vi unngå dette, da listen av saker blir
oppdatert mellom hver innsending.
=> [OPP-1205] resetter sammensatte saker etter innsending av spørsmål

src/app/personside/infotabs/meldinger/traadvisning/__snapshots__/TraadVisningWrapper.test.tsx.snap, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/OppgaveSkjema.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/SkjemaElementOptions.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/__snapshots__/OpprettOppgaveContainer.test.tsx.snap
Kom inn som ønske via teams, feltet er ikke påkrevd og har tidligere også vært mulig å sette tilbake til "Ingen underkategori".
Dette ble blokkert her https://github.com/navikt/modiapersonoversikt/commit/cf23c3519fb5323b1e888c09b59a108109f5ba38 når man la til sperre for å nullstille felt som er påkrevde.
=> [KAIZEN-0] gjøre det mulig å resette `gjelder/underkategori` ved opprettelse av oppgave

.github/workflows/main.yml, .npmrc, package.json, src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap, src/app/personside/infotabs/utbetalinger/totalt utbetalt/__snapshots__/TotaltUtbetaltDetaljer.test.tsx.snap, src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/SammensattUtbetaling.test.tsx.snap, src/app/personside/infotabs/utbetalinger/utbetaling/__snapshots__/UtbetalingsDetaljer.test.tsx.snap, src/app/personside/infotabs/ytelser/__snapshots__/ValgtYtelse.test.tsx.snap, src/app/personside/infotabs/ytelser/__snapshots__/Ytelser.test.tsx.snap, src/app/personside/infotabs/ytelser/arbeidsforhold/__snapshots__/ArbeidsforholdListe.test.tsx.snap, src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrePenger.test.tsx.snap, src/app/personside/infotabs/ytelser/foreldrepenger/__snapshots__/ForeldrepengePeriode.test.tsx.snap, src/app/personside/infotabs/ytelser/pleiepenger/__snapshots__/pleiepenger.test.tsx.snap, src/app/personside/infotabs/ytelser/pleiepenger/arbeidsforhold/__snapshots__/ArbeidsforholdListe.test.tsx.snap, src/app/personside/infotabs/ytelser/sykepenger/sykepengertilfellet/__snapshots__/Sykepengertilfellet.test.tsx.snap, src/app/personside/infotabs/ytelser/utbetalinger/kommendeUtbetalinger/__snapshots__/KommendeUtbetalinger.test.tsx.snap, src/utils/string-utils.test.ts
Tallformat i norge er 123,00 imotsetning til 123.00
Det er også sånn vi viser det i browserenen (chrome) per i dag
Årsaken er at nodejs@<13 bare støttet engelsk locale(small-icu),
og dermed førte til at alt ble formattert på engelsk i testene.
Fra og med nodejs@13 bygges det med full-icu, altså alle locales,
og vi får derfor samme formattering i node som i browseren.
**Anbefaler alle derfor å oppdatere NodeJS til 14.6.0 eller nyere**
14.5.0 og eldre vil sannsynligvis ikke fungere da det har kommet noen feilfixes inn i 14.6.0 på formattering av tall på norsk.
=> [KAIZEN-0] endre snapshots til å ha riktig tallformat

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/oppgave-utils.ts
I tilfeller hvor saksbehandler bytter til tema som ikke har NORM_* prioritet så ville effekten `useNormalPrioritet` ikke endre på state-verdiene (siden den ikke fant NORM_*).
Dette medfører at den gamle prioritet-verdien blir liggende i form-state om man ikke gjør manuelle endringer til prioritet. Dette fører videre til at vi havner i situasjoner hvor vi risikerer å sende inn tema:BID prioritet:NORM_BAR
=> [FAGSYSTEM-123716] legge til fallback om ønsket NORM_prioritet ikke finnes

src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts, src/app/personside/Personoversikt.tsx, src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AvsluttGosysOppgaveSkjema.tsx, src/mock/oppgave-mock.ts, src/models/meldinger/oppgave.ts
ved å hente ut data om oppgaven kan vi gjøre en bedre sjekk av hva som skal være lov i løsning.
F.eks kan vi sikre at ikke-KNA/STO-oppgaver ikke lukkes fra modia, og at saksbehandlere som kommer fra gosys med sånne oppgaver får riktig visning.
=> [OPP-1248] henter oppgave-data fra backend ved overgang fra gosys

src/app/personside/dialogpanel/fortsettDialog/useVisTraadTilknyttetPlukketOppgave.tsx, src/utils/customHooks.ts
i visse edgecases kunne man havne i en setting hvor man alltid hoppet tilbake til melding-lamellen for å sette fokus.
Det er kun ønskelig at dette skal skje en gang ved sidelast, men siden dataene (oppgave/traader) kan ta tid å laste inn
så kan vi ikke bruke useOnMount.
=> [KAIZEN-0] forhindrer melding-fokus å bli satt flere ganger

src/models/temagrupper.ts
for bruk i NKS Utland som miderltidig fiks før Utland er brukbar i heile verdikjeda.
=> [opp-1318] Tilgjengeliggjøring av Øvirg som plukkbar temagruppe f

src/app/personside/dialogpanel/sendMelding/autofullforUtils.ts
Endret til `loggWarning` for å unngå at ekte feilmeldinger kan bli kamuflert
=> [KAIZEN-0] Endret sjekk for enhet

.nais/prod.yaml, .nais/qa-template.yaml, config.yaml
ønsker å teste ut om vi kan resette jwt-token ved å "relaste" modia via  `fetch` slik at vi kan sikre oss mot at fpsak-frontend sitt token blir brukt i løsningen vår
=> [KAIZEN-0] legge til unntak for isso til CSP

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AvsluttGosysOppgaveSkjema.tsx
cea4fa2 legger til sjekk for erSTO for tvungen ferdigstillelse der tidligere GOSYS oppgaver har fått muligheten med feilmelding som resultat.
a5617e6 legger avslutt oppgave fra GOSYS i en ekspanderbartpanel for å gjøre tydligere forskjell på Opprett oppgave og avslutt gosys oppgave
=> [OPP-1332] erSTO sjekk på tvungen ferdigstillese og oppdatert view for avslutt gosys

.nais/prod.yaml, .nais/qa-template.yaml
gjør at brukere blir sendt til samme pod innenfor en periode (300s).
dette gjøres for å fikse en feil som er synlig ved deploy av appen når man har flere podder.
Eksempelvis:
* I prod: index.html peker mot main.abba1234.js
* Ny versjon: index.html peker mot main.acdc9876.js
Ved deploy først en pod bli erstattet, og man havner i en situasjon hvor
man har to forskjellige index.html filer i spill, og disse peker til forskjellige filer.
Ved deploy er det derfor viktig at index.html og påfølgende henting av js-filer går til samme pod.
Om pod 1 gir index.html og kallet for å hente ut js går til pod 2, så vil man få en 404 siden den nye js-filen ikke finnes på den gamle podden.
**Alternativ løsning**:
Dette har tidligere vært løst ved å sette faste navn på javascript/css filene vha …
=> [KAIZEN-0] skru på sessionAffinity

.nais/prod.yaml, .nais/qa-template.yaml, craco.config.js, package-lock.json, package.json, src/app/Routing.tsx
* [KAIZEN-0] fjerne sessionAffinity c1ea182
sessionAffinitiy så ikke ut til å være nok for å unngå at brukere ble sendt til feil pods under deploy.
Vi så derfor fortsatt en del tilfeller av at folk fikk index.html som fallback når man ikke fant ulike javascript-filer.
Siden html ikke er gyldig JS, så feiler parsing av dette og saksbehandler får en blank side.
Dette har sannsynligvisvis vært ett problem i lengre tid, men vært skjult siden pus-fss-frontend gjør samme fallback men med en 404-status.
Når dette skjer så blir ikke JS-filen forsøkt parset, og feilrapporteringen slår ikke inn. Men bruker får fortsatt en blank side.
* [KAIZEN-0] endre navn på filene som blir bygd av CRA 2b0cb17
tar ibruk @navikt/craco-plugins som har plugins for å skru av chunking i CRA.
Før endringen laget vi …
=> [KAIZEN-0] fix/safe deploy

package-lock.json, package.json
biblioteket brukte veldig gammel versjon av `immer` biblioteket,
dette er nå oppdatert og fjerner med det sikkerhetsfeilen; https://github.com/advisories/GHSA-9qmh-276g-x5pj
=> [KAIZEN-0] bump formstate bibliotek

src/app/personside/kontrollsporsmal/SporsmalExtractors.tsx, src/app/personside/visittkort/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort/body/familie/Foreldre.tsx, src/app/personside/visittkort/body/familie/ListeAvBarn.tsx, src/app/personside/visittkort/body/familie/Sivilstand.tsx, src/app/personside/visittkort/header/VisittkortHeader.tsx, src/components/person/HarSammeBosted.tsx, src/components/person/NavnOgAlder.tsx, src/mock/person/personMock.ts, src/models/person/person.ts
TPS sender med informasjon om avdød familiemedlem bor/ ikke bor med bruker. Dette er informasjon vi ikke trenger i Modia og bør filtreres bort,  slik at veileder ikke kommer i skade for å nevne dette for bruker.
=> [OPP-648] fjerner info om bor med bruker dersom person er død

src/app/personside/infotabs/saksoversikt/dokumentvisning/SaksDokumentVisning.tsx
rerendringer fra roten av applikasjonen førte til at pdf-url som er lastet inn og lagret i en blob ble revoked pga useEffect-unmounting.
la derfor til memoizering av komponenten og komponentens props
=> [FAGSYSTEM-165679] fikset bug som gjorde at pdf ble lastet inn flere ganger

src/components/autocomplete-textarea/autocomplete-textarea.tsx, src/mock/context-mock.ts, src/mock/index.ts, src/mock/standardTeksterMock.js
* [KAIZEN-0] fikse urlene satt av mocken 95f27fa
vært noen mindre endringer på urler i det siste, så mocken må oppdateres
* [KAIZEN-0] endret ø til o for en funksjon 0235e87
* [KAIZEN-0] legge til noen eksteren skrivestøttetekster med reelle ider 5af3bf2
gjør at vi kan teste ut mvh/hei lokalt og i heroku selvom de egentlig er avhengige av skrivestøtte-backend
* [KAIZEN-0] koblet flere tekster mot ekstern kilde 8f3d5c8
Følgende er nå koblet mot ekstern definisjon: mvh, mvhen, mvhnn og mvhks
Hovedmotivasjonen bak endringer er endringene i 8f3d5c8, og at nks skal selv få mulighet til å styre sin signatur (nå uten lenke til tiny.cc)
=> [KAIZEN-0] koble mvh-tekst til skrivestøtte

src/app/oppdateringslogg/config/config.tsx
Legger til en ny oppdatering i oppdateringsloggen om at vi har oppdatert oppdateringsloggen slik at folk ikke får opp varsel om ny oppdatering når det ikke er noen.
=> [KAIZEN-0] Legger til ny oppdatering

src/app/personside/infotabs/varsel/Varsel.tsx, src/app/personside/infotabs/varsel/__snapshots__/VarselContainer.test.tsx.snap, src/mock/varsler/varsel-mock.ts, src/redux/varsler/varslerReducer.ts
Viser mer informasjon fra dittnav-varslene, deriblant hvem som er satt som produsent.
Eksempel fra mock-visning:
=> [FAGSYSTEM-168518] legge til visning av ekstra info fra ditt-nav varsler

src/api/api.ts, src/components/popup-boxes/popup-boxes.tsx
følger oppsett fra "LoggetUtModal" slik at vi ivaretar helhetlig look-n-feel.
Lagt opp til 5 ikon-valg som kan styres vha `icon` property, i tillegg har man mulighet til å velge å ikke bruke ett ikon.
`header` og `message` har blitt gjort obligatoriske slik at vi alltid kan være sikre på at ting ser nogenlunde bra ut.
Fra tidligere ble det eksponert fire popup-funksjoner; `alert`, `confirm`, `prompt` og `promptSecret`, og dette styrer hvilke valgmuligheter og input-felter som blir synlig for bruker.
`await alert({ icon: 'error', header: '...', message: '...' })`
`await alert({ icon: 'info', header: '...', message: '...' })`
`await alert({ icon: 'none', header: '...', message: '...' })`
`await alert({ icon: 'ok', header: '...', message: '...' })`
`const result: boolean = await confirm({ …
=> [OPP-1103] oppdatere visuelt uttrykk for popup-boksene

src/app/personside/infotabs/oversikt/OppfolgingOversikt.tsx, src/mock/oppfolging-mock.ts
Etter vi har hentet alle ytelser fra backend vi skal filtere borte ytelser som er Avsluttet
=> [OPP-1359] ikke vise ytelser som er inaktiv i Oppfølgingslamell

src/api/api.ts
Backend (spring-boot) fjerner by-default feilmeldingings teksten av sikkerhetshensyn. Det er behov å skru dette på, men uten ett konkret behov så trenger vi ikke å gjøre dette. Siden vi ikke kommer til å få feilmeldingen fra backend er det heller ikke behov for å prøve å lese feilmeldingen derifra, og vi kan derfor forenkle `postWIthConflictVerification` funksjonen vår litt
=> [OPP-1103] forenkle oppsett for feilmeldinger ved konflikter

src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap, src/app/personside/infotabs/saksoversikt/saksdokumenter/DokumentLenke.tsx, src/mock/saksoversikt/aremark-saksoversikt-mock.ts
…t referans er null
veildere bruke unødvendig tid å åpne dokument som skulle åpnes siden journalpostid og dokumentreferanse er null. i det tilfelle skulle ikke sende forspørsel til backend for hente den dokument. Det er feil i backend hvor som fører til at dokumentreferase og journalpostid dukker opp som null. Det kommer til vi fikse i backend siden
=> [OPP-1370] ikke lage dokumentlenke om journalpost id dokumentid null

src/app/personside/infotabs/oppfolging/GetVeileder.test.ts, src/app/personside/infotabs/oppfolging/OppfolgingDetaljerKomponent.tsx, src/app/personside/infotabs/oppfolging/OppfolgingVisningKomponent.tsx, src/app/personside/infotabs/oppfolging/oppfolging-utils.ts, src/app/personside/infotabs/oversikt/OppfolgingOversikt.tsx, src/mock/oppfolging-mock.ts, src/mock/statiskOppfolgingMock.ts, src/models/oppfolging.ts
Pga tilgangskontroll i veilarboppfolging så må vi gjøre visning av oppfølging mer robust. Dette gjøres ved å håndtere at `null` fra oppfølgingaApiet, spesialhåndtere dette for å gi feedback til saksbehandler.
Det nye nullable-feltet er en erstatting som også fjerner norske spesialtegn. På sikt blir `oppfølging` feltet fjernet
Avhengig av  https://github.com/navikt/modiapersonoversikt-api/pull/392
=> [FAGSYSTEM-178851] ta i bruk nullable oppfolging felt

src/app/personside/kontrollsporsmal/Kontrollsporsmal.tsx
Kontrollspørsmål er i en funksjon bare ibruk av kontaktsenterene, og kan derfor fjernes ved overgang til SF.
=> [OPP-1378] fjerne kontroll spørsmål ved bytte til SF

src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/sendMelding/DialogpanelVelgSak.tsx, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
For å unngå at dialogpanelet fikk dobbel scrolling og ble veldig mye på liten plass valgte jeg å trekke ut velg sak menyen i en modal.
=> [OPP-1278] legger til modal for velg sak i infomelding for å unngå scrolling i dialogpanel

src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/sendMelding/DialogpanelVelgSak.tsx, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap
buttons innenfor ett form vil automatisk fungere som en submit knapp om ikke annet er spesifisert. Ved å sette type="button" skrus denne funksjonaliteten av.
=> [FAGSYSTEM-185782] forhindre submit ved velgsak

src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/body/kontaktinformasjon/dodsbo/Dodsbo.test.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/dodsbo/Dodsbo.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/dodsbo/__snapshots__/Dodsbo.test.tsx.snap
Grunnet endring i backend vil vi nå hente navn fra tredjepartsperson,
som endrer litt på formatet vi får navnet på.
Legger også ved test på dødsbo.
=> [OPP-1390] utvide navn på personadressat

src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/body/fullmakt/Fullmakt.tsx, src/mock/persondata/aremark.ts, src/mock/persondata/personEgenAnsatt.ts, src/mock/persondata/personKode6.ts, src/mock/persondata/personKode6Utland.ts, src/mock/persondata/persondata.ts
Gjør dette slik at vi kan hente beskrivelsen fra kodeverk i stedet for å kun vise koden i frontend
=> [OPP-1390] Endrer fullmakter til å ta inn kodebeskrivelse på område

src/app/personside/visittkort-v2/body/familie/Sivilstand.test.tsx, src/app/personside/visittkort-v2/body/familie/Sivilstand.tsx, src/app/personside/visittkort-v2/body/familie/__snapshots__/Sivilstand.test.tsx.snap
Dersom en person er ugift, så vil `sivilstandRelasjon = null`. Det blir derfor feil å sjekke om sivilstandrelasjon-objektet er null her, da vil man aldri vise ugift-relasjoner.
Legger også til snapshot test.
=> [OPP-1390] fjerne null-sjekk på relasjonobjektet

src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort-v2/body/foreldreansvar/Foreldreansvar.tsx, src/app/personside/visittkort-v2/body/foreldreansvar/__snapshots__/Foreldreansvar.test.tsx.snap, src/app/personside/visittkort-v2/visittkort-utils.ts, src/mock/persondata/aremark.ts, src/mock/persondata/personDeltBosted.ts, src/mock/persondata/personDod.ts, src/mock/persondata/personEgenAnsatt.ts, src/mock/persondata/personKode6.ts, src/mock/persondata/personKode6Utland.ts, src/mock/persondata/personKode7.ts, src/mock/persondata/persondata.ts
Vi utvider foreldreansvar for å vise ident også. I tillegg oppdateres visningen litt.
Det krever en del håndtering rundt feks barn eller foreldre med diskresjonskode. 
Da viser vi feks `Ansvarlig: Ukjent navn`.
PDL fungerer slik at dersom man slår opp et barn, så vil `ansvarsubject` være `null` (for dette er selve personen man slår opp på), og motsatt, dersom man slår opp en forelder, vil `ansvarlig` være `null`. Dermed vil feltene skjules/vises basert på dette.
=> [OPP-1390] nye felter på foreldreansvar

src/app/personside/MainLayout.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/Kontorsperr.tsx, src/utils/customHooks.ts
Fikser så man kan merke kontorsperret på samtalereferat når man bruker det nye endepunktet
=> [FAGSYSTEM-194254] Henter enhet fra nytt endepunkt for kontorsperre

src/app/personside/kontrollsporsmal/SporsmalExtractor.test.ts, src/app/personside/kontrollsporsmal/SporsmalExtractors.tsx
Tidligere lette vi etter partner i en liste av sivilstandrelasjoner.
Ved situasjoner der en person har vært gift og så skilt seg, vil begge disse ligge i lista, selv om giftemålet har opphørt.
Da får vi en situasjon der personen står som ugift i headeren, men som gift i body. Det var tilfellet på aremark i q1 nå.
Dette tar også forebehold om at det første elementet i sivilstand-listen er det nyeste. Her kunne man også sjekket på gyldighetsdato for å være helt sikker.
Aremark i q1:
Dataen man får på aremark, med to sivilstandsrelasjoner:
=> [PROD][OPP-1390] bruke nyeste sivilstandrelasjon i visittkort

src/app/oppdateringslogg/OppdateringsloggContainer.tsx, src/app/oppdateringslogg/config/config.tsx
Vi manglet å rydde opp bruken av VisittkortV2 FT i oppdateringsloggen som ligger i dekoratøren.
=> [OPP-1404] fjerne bruk av FT i oppdateringslogg

src/app/personside/visittkort-v2/body/familie/Familie.tsx
Når en person er 0 år gammel, vil ikke erUnder22 bli true ved forrige løsning, som gjør at foreldrene ikke vises. Dette rettes opp ved å fjerne !! som i javascript caster en variabel til dens boolske verdi, og heller bare sjekke for null.
=> [FAGSYSTEM-199808] fjerne bool-cast på alder i familievisning

src/app/personsok/PersonsokSkjema.tsx, src/components/featureToggle/toggleIDs.ts
muliggjør at man kan skru på pdl-personsok for enkeltbrukere og ikke bare som eksperiment
=> [OPP-1197] legge til egen ft for bruk av pdl-personsok fra frontend

package-lock.json, src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap, src/components/autocomplete-textarea/autocomplete-textarea.tsx
ble etterspurt "aa" som tekst, men siden dette er en brukt bokstav-kombinasjon som kan dukke opp naturlig så legger vi til den litt mer utfyllende "aareg"
=> [FAGSYSTEM-167161] legge til aareg autocomplete

src/app/oppdateringslogg/config/config.tsx, src/app/personside/dialogpanel/__snapshots__/DialogPanel.test.tsx.snap, src/app/personside/dialogpanel/sendMelding/__snapshots__/SendNyMelding.test.tsx.snap, src/components/autocomplete-textarea/autocomplete-textarea.tsx
Basert på hvordan det er skrevet på nav sine hjemmesider: https://www.nav.no/no/bedrift/tjenester-og-skjemaer/aa-registeret-og-a-meldingen
=> [FAGSYSTEM-167161] fjerne typo for aareg-forkortelse

src/app/personside/infotabs/saksoversikt/__snapshots__/SaksoversiktContainer.test.tsx.snap, src/app/personside/infotabs/utbetalinger/__snapshots__/UtbetalingerContainer.test.tsx.snap, src/app/personside/infotabs/utils/InfoTabsScrollBar.tsx, src/app/personside/infotabs/ytelser/__snapshots__/Ytelser.test.tsx.snap
Lamellene for meldinger, Saker, utbetaling og yteler har to-kolonne-layout og derfor interne scrollbars.
For å unngå at innholdet i disse lamellene skal påvirke infotab-komponenten som er deres parent så settes `overflow: hidden`.
Scrollbaren som typisk vil bli lagt til av `InfoTabs` blir dermed borte.
Før:
Etter:
=> [KAIZEN-0] fjerne dobble scrollbars

src/app/innstillinger/modal/innstillinger-modal-form.tsx, src/app/personside/dialogpanel/DialogPanel.tsx, src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.test.tsx, src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/sendMelding/SendNyMelding.test.tsx, src/app/personside/dialogpanel/sendMelding/SendNyMeldingContainer.tsx, src/redux/innstillinger.ts, src/rest/utils/utils.ts, src/test/testStore.ts
gjør det mulig for veileder/saksbehandler å velge en standard for hvor oppgaven som genereres når bruker svarer skal havne.
det er fortsatt mulig å overstyre dette ved utsending av spørsmål.
Innstillinger:
Dialogpanelet:
=> [OPP-1416] legge til innstilling for oppgave destinasjon

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx, src/mock/featureToggle-mock.ts
siden vi ikke har mulighet til å sende inn årsak til sladding, så må det meldes sak i porten.
=> [KAIZEN-0] vise advarsel ved bruk av sladding

src/app/personside/infotabs/meldinger/utils/meldingerUtils.test.ts, src/app/personside/infotabs/meldinger/utils/meldingerUtils.ts
i tilfeller hvor en tråd bare inneholder ett spørsmål fra bruker, men har blitt avsluttet så ønsker vi ikke at tråden skal regnes som ubesvart.
Denne endringen vil gjøre at ikonet for tråden endres, samt at info-alertstripen ikke teller med disse i "Bruker har XX ubesvarte henvendelser"
=> [KAIZEN-0] bytte ikon når tråd er avsluttet

src/app/personside/infotabs/varsel/Varsel.tsx, src/mock/varsler/statiskVarselMock.ts
i tilfeller hvor en tråd bare inneholder ett spørsmål fra bruker, men har blitt avsluttet så ønsker vi ikke at tråden skal regnes som ubesvart.
Denne endringen vil gjøre at ikonet for tråden endres, samt at info-alertstripen ikke teller med disse i "Bruker har XX ubesvarte henvendelser"
=> [PROD][KAIZEN-0] bytte ikon når tråd er avsluttet

src/app/personside/dialogpanel/sendMelding/autofullforUtils.ts, src/app/personside/infotabs/dyplenkeTest/meldingerDyplenker.test.tsx, src/app/personside/infotabs/ytelser/foreldrepenger/foreldrePengerUtils.test.ts, src/app/personside/kontrollsporsmal/KontrollSporsmalKnapper.tsx, src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/header/status/PersonStatus.tsx, src/components/standalone/StandAloneKomponenter.tsx, src/mock/persondata/aremark.ts, src/mock/persondata/persondata.ts, src/mock/personsok/personsokMock.ts, src/mock/saksoversikt/saksoversikt-mock.ts, src/mock/utbetalinger/utbetalinger-mock.ts, src/mock/varsler/varsel-mock.ts, src/mock/ytelse/foreldrepenger-mock.ts, src/mock/ytelse/pleiepenger-mock.ts, src/mock/ytelse/sykepenger-mock.ts, src/test/testStore.ts
siden vi ikke kan garantere at en bruker har fnr endret vi variabelnavnet til personIdent. Dette feltet kan inneholder fnr, dnr, muligens hnr og bnr/npid.
=> [FAGSYSTEM-208044] endre til bruke personident

src/app/personside/infotabs/utbetalinger/filter/Filter.tsx, src/components/MediaQueryAwareRenderer.tsx, src/setupTests.ts
ved smale skjermer tar filter-boksen i utbetaling-lamellen opp nesten hele skjermen.
for å gjøre denne visningen enklere så pakkes denne inn i ett ekspanderbart-panel, slik at boksen kan skjules og mer utbetalingsdata vises.
**Stor skjerm:**
**Liten skjerm:**
=> [FAGSYSTEM-210073] pakke filterboks i ekspanderbartpanel for smale skjermer

src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort-v2/body/familie/ForelderBarnRelasjon.tsx, src/app/personside/visittkort-v2/body/familie/Sivilstand.tsx, src/app/personside/visittkort-v2/body/familie/__snapshots__/Sivilstand.test.tsx.snap, src/app/personside/visittkort-v2/visittkort-utils.ts, src/mock/persondata/aremark.ts, src/mock/persondata/persondata.ts
- [FAGSYSTEM-210465] utvide persondata modell med dodsdato for sivilstand
legger til markerings-interfacet `PersonMedAlderOgDodsdato` for å markere alle interface som har infomasjonen nødvendig for å vise alder eller "(Død)". I første omgang er det snakk om `Person`, `SivilstandRelasjon` og `ForelderBarnRelasjon`.
- [FAGSYSTEM-210465] bruke samme logikk for utledning av alder/død
pga markerings-interfacet `PersonMedAlderOgDodsdato` kan vi nå bruke samme logikk for utledning av alder/død på tvers av `Person` og `ForeldreBarnRelasjon`.
- [FAGSYSTEM-210465] utvide sivilstandvisning til å inkludere informasjon om person er død
=> [FAGSYSTEM-210465] vise informasjon om død for sivilstand

src/app/personside/infotabs/meldinger/traadvisning/TraadVisning.tsx
Operasjonen for avsluttning heter "Avslutt dialog", og det bør derfor samsvare med alertstripen som dukker opp etter gjennomføring
=> [KAIZEN-0] bruke samme terminologi

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx
etter ønske fra brukerstøtte så legger vi til en lenke direkte til skjemaet som skal brukes av veileder for å melde ifra via porten.
=> [PROD][KAIZEN-0] legge til lenke til porten

src/app/personside/visittkort-v2/body/foreldreansvar/Foreldreansvar.tsx
det finnes tilfeller hvor person under foreldreansvar kommer tilbake fra pdl med `ansvarligUtenIdentifikator`, i disse tilfellene har vi bare navn (og alder) på ansvarlig.
I stedet for å vise `(null)` viser vi nå `(Ukjent fnr/dnr)`
=> [KAIZEN-0] ikke vise null om vi mangler ident ved foreldreansvar

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/JournalforingPanel.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.test.ts, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
Salesforce returnerer fagsystems saksid og vanlig saksId. Vi må derfor filtrere på denne id'en istedetfor.
Vi filtrerer også utelukkende på fagsystemSakID og fjerner tema fra sjekken for å unngå trøbbel med duplikat-saker som kan forekomme for UFO/PEN.
=> [OPP-1043] filtrere ut saker basert på fagsystem saksID

src/models/varsel.ts
feltet er ubrukt og nå fjernet fra api
=> [KAIZEN-0] fjerne felt fra dittnav-eventer type

src/app/personsok/PersonsokSkjema.test.ts, src/app/personsok/kontonummer/kontonummerUtils.test.ts, src/app/personsok/kontonummer/kontonummerUtils.ts, src/app/personsok/personsok-utils.ts
Sjekken på om det er gyldig norsk kontonummer er flyttet til en egen tilbakemelding, slik at brukeren vet hva som er feil selv om man oppfyller de to andre kravene om lengde og siffer:
=> [OPP-1462] endre valideringstekst på søk for kontonummer

.nais/prod.yaml, .nais/qa-template.yaml, Dockerfile, proxy.json, proxy.nginx
Sjekken på om det er gyldig norsk kontonummer er flyttet til en egen tilbakemelding, slik at brukeren vet hva som er feil selv om man oppfyller de to andre kravene om lengde og siffer:
=> [PROD][OPP-1462] endre valideringstekst på søk for kontonummer

src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort-v2/body/endringsTekstTPS/EndringstekstTPS.test.tsx, src/app/personside/visittkort-v2/body/endringsTekstTPS/EndringstekstTPS.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/bankkonto/Bankkonto.tsx
Siden bankkonto blir hentet fra TPS, så har vi ikke samme informasjon tilgjengelig på den. Vi trenger derfor å bruke den gamle måten vi viste endringstekst på, hvor vi også håndterte mapping av ident
=> [KAIZEN-0] Legger til egen endringstekst for bankkonto

src/app/personside/dialogpanel/use-draft.ts, src/mock/context-mock.ts, src/mock/draft-mock.ts, src/mock/mock-websocket.ts, src/utils/retry.ts, src/utils/websocket-impl.ts
ved en overgang til obo-tokens mellom apper må kall gjennom en frontend-proxy. Draft-appen kan motta veldig mange kall da vi automatisk synker data hit når folk skriver en melding. For å unngå at alle disse kallene må gjennom frontend-proxy legges det til en måte å oppdatere tekstene via websockets.
=> [KAIZEN-0] legge til muligheten for å oppdatere/slette drafts via websockets

Dockerfile, proxy.json, src/app/internarbeidsflatedecorator/Decorator.tsx, src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekster.tsx, src/app/personside/dialogpanel/sendMelding/standardTekster/sokUtils.tsx, src/app/personside/dialogpanel/use-draft.ts, src/components/autocomplete-textarea/autocomplete-textarea.tsx, src/mock/context-mock.ts, src/mock/index.ts, src/mock/saksbehandlerinnstillinger-mock.ts, src/redux/innstillinger.ts
kall til skrivestotte, draft, innstillinger og modiacontextholder gjøres via proxy slik at cookies kan låses ned til kun å gjelde modiapersonoversikt
=> [KAIZEN-0] gjøre kall til modia-apper via proxy

src/app/personside/visittkort-v2/PersondataDomain.ts, src/app/personside/visittkort-v2/body/kontaktinformasjon/DigitalKontaktinformasjon.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/Kontaktinformasjon.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/epost/Epost.tsx, src/app/personside/visittkort-v2/body/kontaktinformasjon/telefon/Telefon.tsx, src/app/personside/visittkort-v2/header/__snapshots__/VisittkortHeader.test.tsx.snap, src/app/personside/visittkort-v2/header/etiketter/Etiketter.tsx, src/app/personside/visittkort-v2/header/etiketter/ManuellStatusEtikett.tsx, src/app/personside/visittkort-v2/header/etiketter/ReservertIKRREtikett.tsx, src/mock/persondata/aremark.ts, src/mock/persondata/persondata.ts
- [FAGSYSTEM-241955] bytte til nytt informasjonselement for kontaktinformasjon
- [FAGSYSTEM-241955] legge til manuell oppfølging etikett
Avhengig av: https://github.com/navikt/modiapersonoversikt-api/pull/907
=> [FAGSYSTEM-241955] legge til manuell oppfølging etikett

src/app/personside/BegrensetTilgangSide.tsx, src/app/personside/Personoversikt.tsx, src/components/person/BegrensetTilgangBegrunnelse.tsx, src/mock/tilgangskontroll-mock.ts, src/rest/resources/tilgangskontrollResource.tsx
react-query er mer brukt, aktivt forvaltet og støtter refetching mye mer elegant.
=> [KAIZEN-0] bytte ut useFetch for react-query for tilgangskontroll

src/app/PersonOppslagHandler/LyttPåNyttFnrIReduxOgHentAllPersoninfo.tsx, src/app/personside/BegrensetTilgangSide.tsx, src/app/personside/Personoversikt.tsx, src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.test.tsx, src/app/personside/dialogpanel/fortsettDialog/FortsettDialogContainer.tsx, src/app/personside/dialogpanel/fortsettDialog/useOpprettHenvendelse.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/MerkPanel.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/Sladdevalg.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/oppgave/AvsluttGosysOppgaveSkjema.tsx, src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx, src/components/person/BegrensetTilgangBegrunnelse.tsx, src/components/popup-boxes/popup-boxes.tsx, src/mock/tilgangskontroll-mock.ts, src/rest/resources/dialogResource.tsx, src/rest/resources/oppfolgingResource.tsx, src/rest/resources/tildelteoppgaverResource.tsx, src/rest/resources/tilgangskontrollResource.tsx, src/utils/hooks/useTildelteOppgaver.ts
react-query er mer brukt, aktivt forvaltet og støtter refetching mye mer elegant.
=> [KAIZEN-0] bytte ut useFetch for react-query for tildelte oppgaver

preprod-proxy-config.json, proxy-config.json, src/api/config.ts, src/mock/index.ts, src/redux/gjeldendeBruker/actions.ts
Alle kall til api vil bli sendt via proxy, med alle cookies etc.
modiapersonoversikt-api vil derfor fortsatt bruke isso/openAM her frem til vi legger til OBO-direktivet i konfigurasjonen.
Dette gjør det mulig å få  sjekket ytelsen på proxy-appen uten av vi skrur på azuread i produksjon
=> [OPP-1441] sette opp pass-through via proxy-appen

src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/MeldIPortenAdvarsel.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdMeldingerMedArsak.module.css, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdMeldingerMedArsak.tsx, src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/merk/sladdevalg/SladdTradMedArsak.tsx
Legger til samme alert om at sladding må meldes i porten som tidligere vist ved valg av årsak
=> [OPP-1501] legge til melding om porten ved sladding

src/app/personside/dialogpanel/sendMelding/standardTekster/StandardTekster.tsx, src/app/personside/dialogpanel/sendMelding/standardTekster/sokUtils.tsx
`UseQueryResult<T>` bør ikke brukes som en avhengighet til `useEffect` da objektet ikke er stabil over tid.
Ved å endre `useEffect` til å synkronisere mot dataene blir det derimot stabil, og man slipper unna en evig-løkke
=> [KAIZEN-0] fikse evig render-løkke for standardtekster

.nais/prod.yaml, .nais/qa-template.yaml, src/app/personside/infotabs/saksoversikt/SaksDokumentIEgetVindu.tsx
`allowAllUsers: true` (som er default uten `groups`) er en hack fra nais-plattformen, og impliserer egentlig gruppe-tilhørighet til office365-lisens-gruppen.
Ved å spesifisere modiaGenerellTilgang-gruppen (uuid hentet fra azure portal) endrer vi gruppe tilhørigheten til å passe bedre med vårt bruk.
=> [OPP-1441] legge til azure-ad-group

src/api/api.ts, src/app/FetchSessionInfoOgLeggIRedux.tsx, src/app/personside/infotabs/saksoversikt/dokumentvisning/SaksDokumentVisning.tsx, src/rest/resources/oppgaveBehandlerResource.tsx
`allowAllUsers: true` (som er default uten `groups`) er en hack fra nais-plattformen, og impliserer egentlig gruppe-tilhørighet til office365-lisens-gruppen.
Ved å spesifisere modiaGenerellTilgang-gruppen (uuid hentet fra azure portal) endrer vi gruppe tilhørigheten til å passe bedre med vårt bruk.
=> [PROD][OPP-1441] legge til azure-ad-group

src/api/config.ts
ved å slenge på queryparam `azuread` ved lasting av modiapersonoversikt vil alle kall til backend gjøres med azure-ad token og obo-flyt.
etter azure-ad blir skrudd på i produksjon kan vi også bruke dette for å verifisere funksjonaliteten uten at det påvirker veiledere ellers
=> [OPP-1441] teste ut azure-ad-proxy vha queryparam

src/api/config.ts, src/app/personside/infotabs/meldinger/MeldingerContainer.tsx
ved å slenge på queryparam `azuread` ved lasting av modiapersonoversikt vil alle kall til backend gjøres med azure-ad token og obo-flyt.
etter azure-ad blir skrudd på i produksjon kan vi også bruke dette for å verifisere funksjonaliteten uten at det påvirker veiledere ellers
=> [PROD][OPP-1441] teste ut azure-ad-proxy vha queryparam

src/api/config.ts
Klargjøring for azureAd aktivering.
Ved aktiverting av AzureAd vil frontend-containeren begynne å kreve azureAd token.
For veiledere som allerede er inne i løsningen vil dette føre til at de i effekt blir logget ut, og alle kall vil feile frem til de laster siden på nytt og blir logget inn med azuread.
For å minimere konsekvensen av dette kjører vi majoriteten av api-kall direkte mot backend i en overgangsfase
=> [PROD] [KAIZEN-0] gå direkte mot backend

src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBody.test.tsx.snap, src/app/personside/visittkort-v2/body/__snapshots__/VisittkortBodyFeilendeSystemer.test.tsx.snap, src/app/personside/visittkort-v2/body/fullmakt/__snapshots__/Fullmakt.test.tsx.snap, src/utils/telefon-utils.ts, src/utils/telefonUtils.test.ts
Hei!
Vi får rett som det er inn endringsønsker om å endre telefonnummerformatet vi bruker (2+2+2+2) i Modia arbeidsrettet oppfølging og gjøre så det er likt som i personoversikten. Men det viser seg at Modia personoversikt bruker det gamle formatet med 3+2+3. Se [NAVs anbefaling](https://navno.sharepoint.com/sites/intranett-kommunikasjon/SitePages/Datoer,-symboler,-tall-og-valuta.aspx) som igjen er basert på [Språkrådets regler](https://www.sprakradet.no/sprakhjelp/Skriveregler/Dato/#tlf) som ble oppdatert etter [nummerforskriften i 2019](https://lovdata.no/forskrift/2004-02-16-426/§16)
Så tenkte vi nå at å oppdatere formatet hos dere, kanskje kan løse veiledernes behov for å melde inn endringsønsker til oss 🙏 
Si ifra hvis det skulle være noe! 😃 
NB! iPhone formaterer av en eller annen …
=> [KAIZEN-0] Oppdatere telefonnummerformat

src/app/personside/visittkort-v2/VisittkortVisning.tsx
Siden useEffecten kjører på første render logger vi "Accordion lukket" selv når brukeren ikke har interagert med komponenten. Dette skal være fikset ved å ignorere "mount" effecten.
=> Fikse accordion tracking på første render

src/rest/resources/sakstemaResource.tsx
Spring 3 fjernet implisitt match av trailing slash.
=> Fjern trailing slash fra API url

src/app/AppContainer.tsx
Fjernet `height: 0` etter vite oppgradering ettersom det ødela height i prod, men det ser ut til at
hacken gjorde at dynamisk height i containeren fungerte ordentlig.
Med denne fiksen er det mulig å scrolle i mye innhold igjen :)
=> Fiks overflow problem i hoved konteiner

src/index.tsx, vite.config.ts
Dette gjør det mulig å sette en token fra [token generator](https://docs.nais.io/security/auth/azure-ad/usage/#token-generator) i env variablen `LOCAL_TOKEN`. Da vil requests til `/proxy` sendes til vite og proxies videre til proxien som kjører i dev (Q2) med tokenen. 
TLDR så vil man nå kunne utvikle frontenden lokalt mot hele dev-miljøet som kjører i gcp :)
=> Aktiver proxy til dev-miljø ved lokal utvikling

.nais/prod.yaml, .nais/qa-template.yaml, src/app/AppContainer.tsx, src/app/internarbeidsflatedecorator/Decorator.tsx, src/app/internarbeidsflatedecorator/LandingPage.tsx, src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx, src/app/routes/routing.tsx
Tanken her er at vi kan endre URLen som Modia-ikonet i Applikasjonsportalen peker på til den nye ingressen `https://modiaflate.intern.nav.no/landingpage`.
Vi kan også putte en redirect på den gamle URLen om det er slik at folk bruker den gamle URLen direkte.
Har ikke prøvd å opprette Ingress med en spesifikk path før, men det skal vist [være mulig](https://doc.nav.cloud.nais.io/workloads/application/how-to/expose/).
Stopp meg om jeg er på bærtur 🙏
=> Landing page

src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx, src/app/internarbeidsflatedecorator/useHandleGosysUrl.ts, src/app/personside/Personoversikt.tsx, src/redux/gjeldendeBruker/reducer.ts, src/redux/gjeldendeBruker/types.ts
Et par ting som skjer her:
Hvis man lenket til f.eks `/person/:fnr/saker`, så ville ikke fnr være i redux med en gang, og
`useEffect`en i Personoversikt komponenten ville route tilbake til hovedsiden, før redux er
oppdatert og man sendes tilbake med et gyldig fnr. Altså mister man `/sake` urlEn. Nå setter vi en
state på om fnr er "klart" i redux, med en timeout, slik at vi venter med å kjøre validation til fnr
er satt i redux.
Denne ble glemt i routing/fnr-i-url endringene og gjorde at ting ikke skjedde i riktig rekkefølge,
ettersom den redirectet til "riktig" url en render-sykel for sent, og da hadde contexten lastet inn
forrige person og satt denne i redux før gosys-url handleren rakk å gjøre det.
Nå setter vi fnr i redux, dispatcher route replacement med en gang slik at ting skjer i …
=> Fikse gosys URL handler & tab routing med fnr

src/app/internarbeidsflatedecorator/personsokKnapp.less, src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
Noe rart som har skjedd med stylingen til pilen under avansert søk knappen i dekoratøren. Jeg tenkte det var like greit å bare fjerne den ettersom den så litt out of place ut.
Før:
Etter:
=> Fikse rar styling på avansert søk knapp

src/app/personside/Personoversikt.tsx, src/app/personside/infotabs/saksoversikt/SaksDokumentIEgetVindu.tsx, src/components/VentPaaPersonLastet.tsx
Fikser en bug der åpning av dokumentsiden prøvde å laste inn dokumenter
for bruker før fnr var satt, noe som propagerer dårlige requests rundt
omkring i verdikjeden.
=> Sikre at personnummer er lastet inn før bruk

src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx
I teorien skal dette allerede fungere med route matchen og redux
dispatchen som er i Routing. Men den er veldig avhengig av at ting
rendrer og skjer i en spesifikk rekkefølge. Her henter vi ut Fnr fra
URLen direkte i dekoratøren slik som med fnr fra query parametre. Det
gjør at vi kan være sikre på at vi henter riktig fnr til dekoratøren
uavhengig av hvordan event loopen i appen er.
=> Fiks henting av fnr fra URL

.nais/dev.yaml, .nais/prod.yaml
Personoversikt i prod er veldig CPU-bound og varierer fra 5m CPU til 300m CPU i peak business hours, så beholder litt juice på den så den blir prioritert under load.
=> Skaler ned ressursbruk

proxy-config-dev.json, proxy-config-prod.json, src/api/config.ts
Når vi bruker autogenerert klient fra openAPI schema så er /rest med i
URLene og det er litt styr å fjerne den. Vi normaliserer og fjerner
/rest fra proxy urlen isteden.
=> Fjerne /rest fra proxy url til API

src/app/personside/BegrensetTilgangSide.tsx
React-collapse i nav frontend Ekspanderbartpanel virker å ha en satt height
og overflow: hide på windows av en eller annen grunn.
Vi resetter dette og håper det løser problemet.
=> Fikse bug på windows med overflow

src/app/internarbeidsflatedecorator/Decorator.tsx, src/components/featureToggle/FeatureToggle.tsx, src/components/featureToggle/IfFeatureToggleOff.tsx, src/components/featureToggle/IfFeatureToggleOn.tsx, src/routes/__root.tsx, src/utils/HandleLegacyUrls.tsx
FeatureToggle komponentene viser loadere når man venter på data. Men de tar ikke hensyn til at det
som vises ikke er vanlige block komponenter. Dette fjerner to loadere som dukker opp i et halvt
sekund pga. feature toggling på avansert søk.
=> Fjerne overflødige loadere

src/utils/hooks/usePaginering.tsx
Antakeligvis i en refaktorering har det skjedd en glippe og der vi
henter ut verdien for å sammenlikne med manglet det en parantes slik at
funksjonen alltid returnerte `true` og dermed resatte paginering til 0
hver gang useEffecten kjørte.
=> Fiks bug i paginering m. feil compare i findIndex

src/app/personside/infotabs/utbetalinger/Utbetalinger.test.tsx, src/app/personside/infotabs/utbetalinger/Utbetalinger.tsx, src/app/personside/infotabs/utbetalinger/filter/UtbetalingFilter.tsx, src/app/personside/infotabs/utbetalinger/filter/YtelseValg.tsx, src/app/personside/infotabs/utbetalinger/utils/utbetalinger-utils.test.tsx, src/mock/utbetalinger/utbetalinger-mock.ts, src/redux/utbetalinger/types.ts, src/redux/utbetalinger/utbetalingerReducer.ts
I utbetalinger var det logikk for å legge til ytelser som default true i
filteret når det kom inn nye utbetalinger. Dette funket ikke da
komponenten remountet og onComponentUpdate ikke lenger fungerer for å se
hvilke ytelser som er nye. Vi endrer det til at filteret kan holde styr
på både hilke som er valgt og hvilke valgmuligheter som _finnes_ ved å
gjøre den om til et objekt.
=> Ikke resett ytelsefilter ved endring i periode

index.html, src/app/internarbeidsflatedecorator/useDecoratorConfig.tsx, src/utils/analytics.ts
Prøver på nytt med denne.
I dekoratøren tracker vi outbound (og innbound) links sånn her: https://umami.is/docs/track-outbound-links
Problemet med denne måten å tracke på er at nokon gongar så blocker requesten til Umami page navigation.
For å hindre dette sender me no request via Beacon API.
I tillegg hadde me satt opp eigen tracking på onLinkClick i dekoratøren som gjer at me har dobbelt tracking i dekoratøren, så har fjerna den.
Har lagt til tom referrer om den ikkje eksisterer i payloaden då dette gav ein feil sist.
=> Send umami requests via beacon
